// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:17.100Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const arugulaSaladWithFigsProsciuttoWalnutsAndParmesan = {
  id: "atk_arugula-salad-with-figs-prosciutto-walnuts-and-parmesan",
  name: "Arugula Salad with Figs, Prosciutto, Walnuts, and Parmesan",
  slug: "arugula-salad-with-figs-prosciutto-walnuts-and-parmesan",
  metadata: {
    timeBand: "FAST",
    estimatedMinutes: 35,
    equipmentTags: [
      "LARGE_SKILLET"
    ],
    leftoverStrategy: "EXPECTED",
    baseServings: 6,
    yieldText: "SERVES 6"
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "extra-virgin-olive-oil",
          displayName: "extra-virgin olive oil",
          amount: 4,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "thinly-sliced-prosciutto-cut-into-1-4-inch-strips",
          displayName: "thinly sliced prosciutto, cut into 1/4-inch strips",
          amount: 2,
          unit: "OZ",
          criticality: "CRITICAL",
          kind: "PROTEIN",
          shoppingCategory: "MEAT_SEAFOOD",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "balsamic-vinegar",
          displayName: "balsamic vinegar",
          amount: 3,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "VINAIGRETTE"
        },
    {
          ingredientId: "raspberry-jam",
          displayName: "raspberry jam",
          amount: 1,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "VINAIGRETTE"
        },
    {
          ingredientId: "dried-figs-stems-removed-fruit-chopped-into-1-4-inch-pieces",
          displayName: "dried figs, stems removed, fruit chopped into 1/4-inch pieces",
          amount: 0.5,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "FRUIT",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          component: "VINAIGRETTE"
        },
    {
          ingredientId: "small-shallot-minced-about-1-tablespoon",
          displayName: "small shallot, minced (about 1 tablespoon)",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          component: "VINAIGRETTE"
        },
    {
          ingredientId: "table-salt-and-ground-black-pepper",
          displayName: "Table salt and ground black pepper",
          amount: 1,
          unit: "UNIT",
          criticality: "NON_CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "TO_TASTE"
        },
    {
          ingredientId: "loosely-packed-baby-arugula-about-5-cups-washed-and-dried",
          displayName: "loosely packed baby arugula (about 5 cups), washed and dried",
          amount: 5,
          unit: "OZ",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "walnuts-toasted-and-chopped",
          displayName: "walnuts, toasted and chopped",
          amount: 0.5,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          allergens: [
            "TREE_NUT"
          ]
        },
    {
          ingredientId: "parmesan-cheese-shaved-into-thin-strips-with-a-vegetable-peeler",
          displayName: "Parmesan cheese, shaved into thin strips with a vegetable peeler",
          amount: 2,
          unit: "OZ",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        }
  ],
  preflight: [],
  steps: [
    {
          stepNumber: 1,
          instruction: "Heat 1 tablespoon of the oil in a 10-inch nonstick skillet over medium heat; add the prosciutto and fry until crisp, stirring frequently, about 7 minutes. Using a slotted spoon, transfer to a paper towel–lined plate and set aside to cool."
        },
    {
          stepNumber: 2,
          instruction: "Whisk the vinegar and jam together in a medium microwave-safe bowl until combined; stir in the figs. Cover with plastic wrap, cut several steam vents in the plastic, and microwave on high until the figs are plump, 30 seconds to 1 minute. Whisk in the remaining 3 tablespoons oil, the shallot, 1/4 teaspoon salt, and 1/8 teaspoon pepper until combined. Cool to room temperature."
        },
    {
          stepNumber: 3,
          instruction: "Toss the arugula with the vinaigrette in a large bowl; season with salt and pepper to taste. Divide the salad among individual plates; top each with a portion of the prosciutto, walnuts, and Parmesan. Serve."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ],
  recipeAllergens: [
    "TREE_NUT",
    "DAIRY"
  ]
} satisfies Recipe;
