// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:17.110Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const asparagusHamAndGruyReFrittata = {
  id: "atk_asparagus-ham-and-gruy-re-frittata",
  name: "Asparagus, Ham, and Gruyère Frittata",
  slug: "asparagus-ham-and-gruy-re-frittata",
  metadata: {
    timeBand: "NORMAL",
    estimatedMinutes: 45,
    equipmentTags: [
      "OVEN"
    ],
    leftoverStrategy: "EXPECTED",
    baseServings: 6,
    yieldText: "SERVES 6 to 8"
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "large-eggs",
          displayName: "large eggs",
          amount: 12,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "half-and-half",
          displayName: "half-and-half",
          amount: 3,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "table-salt",
          displayName: "table salt",
          amount: 0.5,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "pepper",
          displayName: "pepper",
          amount: 0.25,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "olive-oil",
          displayName: "olive oil",
          amount: 2,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "asparagus-tough-ends-trimmed-spears-cut-on-the-bias-into-1-4-inch-pieces",
          displayName: "asparagus, tough ends trimmed, spears cut on the bias into 1/4-inch pieces",
          amount: 8,
          unit: "OZ",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "1-4-inch-thick-deli-ham-cut-into-1-2-inch-cubes-about-3-4-cup",
          displayName: "1/4-inch-thick deli ham, cut into 1/2-inch cubes (about 3/4 cup)",
          amount: 4,
          unit: "OZ",
          criticality: "CRITICAL",
          kind: "PROTEIN",
          shoppingCategory: "MEAT_SEAFOOD",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "medium-shallot-minced-about-3-tablespoons",
          displayName: "medium shallot, minced (about 3 tablespoons)",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "gruy-re-cheese-cut-into-1-4-inch-cubes-about-3-4-cup",
          displayName: "Gruyère cheese, cut into 1/4-inch cubes (about 3/4 cup)",
          amount: 3,
          unit: "OZ",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        }
  ],
  preflight: [],
  steps: [
    {
          stepNumber: 1,
          instruction: "Adjust an oven rack about 5 inches from the broiler element and heat the broiler. Whisk the eggs, half-and-half, salt, and pepper together in a medium bowl. Set aside."
        },
    {
          stepNumber: 2,
          instruction: "Heat the oil in a 12-inch ovensafe nonstick skillet over medium heat until shimmering; add the asparagus and cook, stirring occasionally, until lightly browned and almost tender, about 3 minutes. Add the ham and shallot and cook until the shallot softens, about 2 minutes."
        },
    {
          stepNumber: 3,
          instruction: "Stir the Gruyère into the eggs; add the egg mixture to the skillet and cook, using a heatproof rubber spatula to stir and scrape the bottom of the skillet, until large curds form and the spatula begins to leave a wake but the eggs are still very wet, about 2 minutes. Shake the skillet to distribute the eggs evenly and cook without stirring to let the bottom set, about 30 seconds."
        },
    {
          stepNumber: 4,
          instruction: "Slide the skillet under the broiler and cook until the surface is puffed and spotty brown, yet the center remains slightly wet and runny when cut into with a paring knife, 3 to 4 minutes. Using a potholder (the skillet handle will be hot), remove the skillet from the oven and let stand for 5 minutes to finish cooking; using the spatula, loosen the frittata from the skillet and slide it onto a platter or cutting board. Cut into wedges and serve."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ],
  recipeAllergens: [
    "DAIRY"
  ]
} satisfies Recipe;
