// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:17.300Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const barbecuedPulledPork = {
  id: "atk_barbecued-pulled-pork",
  name: "Barbecued Pulled Pork",
  slug: "barbecued-pulled-pork",
  metadata: {
    timeBand: "PROJECT",
    estimatedMinutes: 360,
    equipmentTags: [
      "GRILL",
      "OVEN"
    ],
    leftoverStrategy: "EXPECTED",
    baseServings: 8,
    yieldText: "SERVES 8"
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "6-to-8-pound-bone-in-boston-butt-roast",
          displayName: "(6- to 8-pound) bone-in Boston butt roast",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "PROTEIN",
          shoppingCategory: "MEAT_SEAFOOD",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "dry-rub-for-barbecue-recipe-follows",
          displayName: "Dry Rub for Barbecue (recipe follows)",
          amount: 0.75,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "RUB"
        },
    {
          ingredientId: "wood-chips-soaked-in-water-for-15-minutes-and-drained",
          displayName: "wood chips, soaked in water for 15 minutes and drained",
          amount: 4,
          unit: "CUP",
          criticality: "NON_CRITICAL",
          kind: "OTHER",
          shoppingCategory: "OTHER",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "13-by-9-inch-disposable-aluminum-roasting-pan",
          displayName: "(13 by 9-inch) disposable aluminum roasting pan",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "OTHER",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "barbecue-sauce-recipe-follows",
          displayName: "barbecue sauce (recipe follows)",
          amount: 2,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "SAUCE"
        }
  ],
  preflight: [
    {
          label: "Refrigerate pork with dry rub",
          durationMinutes: 180,
          type: "MARINATE"
        },
    {
          label: "Bring roast to room temperature",
          durationMinutes: 60,
          type: "LONG_PREP"
        }
  ],
  steps: [
    {
          stepNumber: 1,
          instruction: "Pat pork dry with paper towels, then massage dry rub into meat. Wrap meat in plastic wrap and refrigerate for at least 3 hours or up to 3 days."
        },
    {
          stepNumber: 2,
          instruction: "At least 1 hour prior to cooking, remove roast from refrigerator, unwrap, and let sit at room temperature. Using 2 large pieces of heavy-duty aluminum foil, wrap soaked chips in 2 foil packets and cut several vent holes in tops."
        },
    {
          stepNumber: 3,
          instruction: "Set roast in disposable pan, place on cool side of grill, and cook for 3 hours. During final 20 minutes of cooking, adjust oven rack to lower-middle position and heat oven to 325 degrees."
        },
    {
          stepNumber: 4,
          instruction: "Wrap disposable pan with heavy-duty foil and cook in oven until meat is fork-tender, about 2 hours."
        },
    {
          stepNumber: 5,
          instruction: "Carefully slide foil-wrapped pan with roast into brown paper bag. Crimp end shut and let rest for 1 hour."
        },
    {
          stepNumber: 6,
          instruction: "Transfer roast to carving board and unwrap. Separate roast into muscle sections, removing fat, if desired, and tearing meat into shreds with your fingers. Place shredded meat in large bowl and toss with 1 cup barbecue sauce. Serve, passing remaining sauce separately."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ]
} satisfies Recipe;
