// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:17.459Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const beetsWithLemonAndAlmonds = {
  id: "atk_beets-with-lemon-and-almonds",
  name: "Beets with Lemon and Almonds",
  slug: "beets-with-lemon-and-almonds",
  metadata: {
    timeBand: "NORMAL",
    estimatedMinutes: 75,
    equipmentTags: [
      "DUTCH_OVEN"
    ],
    leftoverStrategy: "EXPECTED",
    baseServings: 5,
    yieldText: "SERVES 4 to 6"
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "beets-trimmed-and-halved-horizontally",
          displayName: "beets, trimmed and halved horizontally",
          amount: 1.5,
          unit: "LB",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "water",
          displayName: "water",
          amount: 1.25,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "table-salt-divided",
          displayName: "table salt, divided",
          amount: 0.75,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "distilled-white-vinegar",
          displayName: "distilled white vinegar",
          amount: 3,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "packed-light-brown-sugar",
          displayName: "packed light brown sugar",
          amount: 1,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "shallot-sliced-thin",
          displayName: "shallot, sliced thin",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "grated-lemon-zest",
          displayName: "grated lemon zest",
          amount: 1,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "FRUIT",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "pepper",
          displayName: "pepper",
          amount: 0.25,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "TO_TASTE"
        },
    {
          ingredientId: "whole-almonds-toasted-and-chopped",
          displayName: "whole almonds, toasted and chopped",
          amount: 0.5,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          allergens: [
            "TREE_NUT"
          ]
        },
    {
          ingredientId: "chopped-fresh-mint",
          displayName: "chopped fresh mint",
          amount: 2,
          unit: "TBSP",
          criticality: "NON_CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "APPROXIMATE"
        },
    {
          ingredientId: "chopped-fresh-thyme",
          displayName: "chopped fresh thyme",
          amount: 1,
          unit: "TSP",
          criticality: "NON_CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PRODUCE",
          quantityKind: "APPROXIMATE"
        }
  ],
  preflight: [],
  steps: [
    {
          stepNumber: 1,
          instruction: "Place beets, cut side down, in single layer in 11-inch straight-sided sauté pan or Dutch oven. Add water and 1/4 teaspoon salt; bring to simmer over high heat. Reduce heat to low; cover; and simmer until beets are tender and tip of paring knife inserted into beets meets no resistance, 45 to 50 minutes."
        },
    {
          stepNumber: 2,
          instruction: "Transfer beets to cutting board. Increase heat to medium-high and reduce cooking liquid, stirring occasionally, until pan is almost dry, 5 to 6 minutes. Add vinegar and sugar, return to boil, and cook, stirring constantly with heat-resistant spatula, until spatula leaves wide trail when dragged through glaze, 1 to 2 minutes. Remove pan from heat."
        },
    {
          stepNumber: 3,
          instruction: "When beets are cool enough to handle, rub off skins with paper towel or clean dish towel and cut into 1/2-inch wedges. Add beets, shallot, lemon zest, pepper, and remaining 1/2 teaspoon salt to glaze and toss to coat. Transfer beets to serving dish; sprinkle with almonds, mint, and thyme; and serve."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ],
  recipeAllergens: [
    "TREE_NUT"
  ]
} satisfies Recipe;
