// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:17.510Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const bestButtermilkWaffles = {
  id: "atk_best-buttermilk-waffles",
  name: "Best Buttermilk Waffles",
  slug: "best-buttermilk-waffles",
  metadata: {
    timeBand: "FAST",
    estimatedMinutes: 30,
    equipmentTags: [
      "OVEN"
    ],
    leftoverStrategy: "EXPECTED",
    yieldText: "MAKES eight 7-inch round waffles",
    baseServings: 8
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "10-ounces-unbleached-all-purpose-flour",
          displayName: "(10 ounces) unbleached all-purpose flour",
          amount: 2,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "CARB",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "dried-buttermilk-powder",
          displayName: "dried buttermilk powder",
          amount: 0.5,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "sugar",
          displayName: "sugar",
          amount: 1,
          unit: "TBSP",
          criticality: "NON_CRITICAL",
          kind: "CARB",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "table-salt",
          displayName: "table salt",
          amount: 0.75,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "baking-soda",
          displayName: "baking soda",
          amount: 0.5,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "sour-cream",
          displayName: "sour cream",
          amount: 0.5,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "large-eggs",
          displayName: "large eggs",
          amount: 2,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "vegetable-oil",
          displayName: "vegetable oil",
          amount: 0.25,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "vanilla-extract",
          displayName: "vanilla extract",
          amount: 0.25,
          unit: "TSP",
          criticality: "NON_CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "unflavored-seltzer-water-or-club-soda",
          displayName: "unflavored seltzer water or club soda",
          amount: 1.25,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "OTHER",
          quantityKind: "FIXED"
        }
  ],
  preflight: [],
  steps: [
    {
          stepNumber: 1,
          instruction: "Adjust oven rack to middle position and heat oven to 250 degrees. Set wire rack over rimmed baking sheet and place baking sheet in oven. Whisk flour, buttermilk powder, sugar, salt, and baking soda in large bowl to combine. Whisk sour cream, eggs, oil, and vanilla in medium bowl to combine. Gently stir seltzer into wet ingredients. Make well in center of dry ingredients and pour in wet ingredients. Gently stir until just combined. Batter should remain slightly lumpy with streaks of flour."
        },
    {
          stepNumber: 2,
          instruction: "Heat waffle iron and bake waffles according to manufacturer’s instructions (use about 1/3 cup for 7-inch round iron). Transfer waffles to rack in warm oven and hold for up to 10 minutes before serving."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ],
  recipeAllergens: [
    "DAIRY"
  ]
} satisfies Recipe;
