// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:17.780Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const braisedChickenThighsWithLemonSpicesAndTornBasil = {
  id: "atk_braised-chicken-thighs-with-lemon-spices-and-torn-basil",
  name: "Braised Chicken Thighs with Lemon, Spices, and Torn Basil",
  slug: "braised-chicken-thighs-with-lemon-spices-and-torn-basil",
  metadata: {
    timeBand: "NORMAL",
    estimatedMinutes: 120,
    leftoverStrategy: "EXPECTED",
    baseServings: 4,
    yieldText: "SERVES 4 to 6",
    equipmentTags: []
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "use-a-small-saucepan-or-skillet-to-crush-the-coriander-seeds-serve-with-potatoes-rice-or-buttered-noodles",
          displayName: "Use a small saucepan or skillet to crush the coriander seeds. Serve with potatoes, rice, or buttered noodles.",
          amount: 1,
          unit: "UNIT",
          criticality: "NON_CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "5-to-7-ounce-bone-in-chicken-thighs-trimmed",
          displayName: "(5- to 7-ounce) bone-in chicken thighs, trimmed",
          amount: 8,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "PROTEIN",
          shoppingCategory: "MEAT_SEAFOOD",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "table-salt",
          displayName: "table salt",
          amount: 1.25,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "pepper",
          displayName: "pepper",
          amount: 0.5,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "vegetable-oil",
          displayName: "vegetable oil",
          amount: 1,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "shallot-minced",
          displayName: "shallot, minced",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "cloves-minced",
          displayName: "cloves, minced",
          amount: 2,
          unit: "GRAM",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "ground-cumin",
          displayName: "ground cumin",
          amount: 1,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "ground-coriander",
          displayName: "ground coriander",
          amount: 0.5,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "chicken-broth",
          displayName: "chicken broth",
          amount: 1.5,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "grated-lemon-zest-plus-1-2-cup-juice-3-lemons",
          displayName: "grated lemon zest plus 1/2 cup juice (3 lemons)",
          amount: 0.5,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "FRUIT",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "water",
          displayName: "water",
          amount: 2,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "cornstarch",
          displayName: "cornstarch",
          amount: 1.5,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "coriander-seeds-lightly-crushed",
          displayName: "coriander seeds, lightly crushed",
          amount: 1,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "unsalted-butter-cut-into-2-pieces",
          displayName: "unsalted butter, cut into 2 pieces",
          amount: 2,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "large-basil-leaves-torn-into-pieces",
          displayName: "large basil leaves, torn into pieces",
          amount: 10,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          component: "GARNISH"
        }
  ],
  preflight: [],
  steps: [
    {
          stepNumber: 1,
          instruction: "Adjust oven rack to lower-middle position and heat oven to 325 degrees. Pat chicken dry with paper towels and sprinkle both sides with salt and pepper. Heat oil in 12-inch ovensafe skillet over medium heat until shimmering. Add chicken, skin side down, and cook, without moving it, until well browned, about 8 minutes. Using tongs, flip chicken and brown on second side, about 3 minutes. Transfer chicken to large plate."
        },
    {
          stepNumber: 2,
          instruction: "Pour off all but 2 tablespoons fat from skillet. Add shallot and garlic and cook, stirring frequently, until garlic is golden brown, about 11/2 minutes. Add cumin and ground coriander and cook, stirring constantly, for 1 minute. Add broth and lemon juice; bring to simmer, scraping up any browned bits. Return chicken to skillet skin side up (skin will be above surface of liquid). Transfer skillet to oven and bake, uncovered, until chicken registers 195 degrees, 35 to 40 minutes. Whisk water and cornstarch together in small bowl; set aside."
        },
    {
          stepNumber: 3,
          instruction: "Using tongs, transfer chicken to serving platter and tent with aluminum foil. Place skillet over high heat. Stir coriander seeds into liquid and bring to boil. Cook, occasionally scraping side of skillet to incorporate fond, until sauce is thickened and reduced to 11/2 cups, 8 to 10 minutes. Adjust heat to medium-low. Whisk cornstarch mixture to recombine and then whisk into sauce and simmer until thickened, about 1 minute. Off heat, whisk in lemon zest and butter. Season with salt and pepper to taste. Pour sauce around chicken, top with basil, and serve."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ],
  recipeAllergens: [
    "DAIRY"
  ]
} satisfies Recipe;
