// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:17.942Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const broccoliCheeseSoup = {
  id: "atk_broccoli-cheese-soup",
  name: "Broccoli-Cheese Soup",
  slug: "broccoli-cheese-soup",
  metadata: {
    timeBand: "NORMAL",
    estimatedMinutes: 60,
    equipmentTags: [
      "DUTCH_OVEN",
      "BLENDER"
    ],
    leftoverStrategy: "EXPECTED",
    baseServings: 6,
    yieldText: "SERVES 6 to 8"
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "why-this-recipes-works-we-were-after-a-soup-with-pure-broccoli-flavor-that-wasn-t-hiding-behind-the-cream-or-the-cheese-overcooked-broccoli-has-a-sulfurous-flavor-but-we-discovered-when-we-cooked-our-broccoli-beyond-the-point-of-just-overcooked-for-a-full-hour-those-sulfur-containing-compounds-broke-down-leaving-behind-intense-nutty-broccoli-its-texture-was-fairly-soft-but-that-was-perfect-for-use-in-a-soup-adding-baking-soda-to-the-pot-sped-up-the-process-shortening-the-broccoli-s-cooking-time-to-a-mere-20-minutes-a-little-spinach-lent-bright-green-color-to-the-soup-without-taking-over-the-flavor-after-adding-cheddar-and-parmesan-we-had-a-soup-so-full-of-flavor-and-richness-that-it-didn-t-even-need-the-typical-cream-serve-with-buttery-croutons-this-page-if-desired-to-make-a-vegetarian-version-of-this-soup-substitute-vegetable-broth-for-the-chicken-broth",
          displayName: "WHY THIS RECIPES WORKS We were after a soup with pure broccoli flavor that wasn’t hiding behind the cream or the cheese. Overcooked broccoli has a sulfurous flavor, but we discovered when we cooked our broccoli beyond the point of just overcooked—for a full hour—those sulfur-containing compounds broke down, leaving behind intense, nutty broccoli. Its texture was fairly soft, but that was perfect for use in a soup. Adding baking soda to the pot sped up the process, shortening the broccoli’s cooking time to a mere 20 minutes. A little spinach lent bright green color to the soup without taking over the flavor. After adding cheddar and Parmesan, we had a soup so full of flavor and richness that it didn’t even need the typical cream. Serve with Buttery Croutons (this page), if desired. To make a vegetarian version of this soup, substitute vegetable broth for the chicken broth.",
          amount: 1,
          unit: "UNIT",
          criticality: "NON_CRITICAL",
          kind: "OTHER",
          shoppingCategory: "OTHER",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "unsalted-butter",
          displayName: "unsalted butter",
          amount: 2,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "broccoli-florets-chopped-into-1-inch-pieces-stems-peeled-and-sliced-1-4-inch-thick",
          displayName: "broccoli, florets chopped into 1-inch pieces, stems peeled and sliced 1/4 inch thick",
          amount: 2,
          unit: "LB",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "onion-chopped-coarse",
          displayName: "onion, chopped coarse",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "cloves-minced",
          displayName: "cloves, minced",
          amount: 2,
          unit: "GRAM",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "dry-mustard",
          displayName: "dry mustard",
          amount: 1.5,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "table-salt",
          displayName: "table salt",
          amount: 1,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "pinch-cayenne-pepper",
          displayName: "Pinch cayenne pepper",
          amount: 1,
          unit: "UNIT",
          criticality: "NON_CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "water-divided",
          displayName: "water, divided",
          amount: 34,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "baking-soda",
          displayName: "baking soda",
          amount: 0.25,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "chicken-broth",
          displayName: "chicken broth",
          amount: 2,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "PROTEIN",
          shoppingCategory: "MEAT_SEAFOOD",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "baby-spinach-about-2-cups",
          displayName: "baby spinach (about 2 cups)",
          amount: 2,
          unit: "OZ",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "sharp-cheddar-cheese-shredded-3-4-cup",
          displayName: "sharp cheddar cheese, shredded (3/4 cup)",
          amount: 3,
          unit: "OZ",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "parmesan-cheese-grated-fine-3-4-cup-plus-extra-for-serving",
          displayName: "Parmesan cheese, grated fine (3/4 cup), plus extra for serving",
          amount: 1.5,
          unit: "OZ",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          component: "SOUP",
          allergens: [
            "DAIRY"
          ]
        }
  ],
  preflight: [],
  steps: [
    {
          stepNumber: 1,
          instruction: "Melt butter in Dutch oven over medium-high heat. Add broccoli, onion, garlic, mustard, salt, and cayenne and cook, stirring frequently, until fragrant, about 6 minutes. Add 1 cup water and baking soda. Bring to simmer, cover, and cook until broccoli is very soft, about 20 minutes, stirring once during cooking."
        },
    {
          stepNumber: 2,
          instruction: "Add broth and 2 cups water and increase heat to medium-high. When mixture begins to simmer, stir in spinach and cook until wilted, about 1 minute. Transfer half of soup to blender, add cheddar and Parmesan, and process until smooth, about 1 minute. Transfer soup to medium bowl and repeat with remaining soup. Return soup to Dutch oven, place over medium heat and bring to simmer. Adjust consistency of soup with up to 1 cup water. Season with salt and pepper to taste. Serve, passing extra Parmesan."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ],
  recipeAllergens: [
    "DAIRY"
  ]
} satisfies Recipe;
