// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:18.052Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const butternutSquashRisotto = {
  id: "atk_butternut-squash-risotto",
  name: "Butternut Squash Risotto",
  slug: "butternut-squash-risotto",
  metadata: {
    timeBand: "NORMAL",
    estimatedMinutes: 75,
    equipmentTags: [
      "LARGE_SKILLET"
    ],
    leftoverStrategy: "EXPECTED",
    baseServings: 5,
    yieldText: "SERVES 4 to 6"
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "olive-oil",
          displayName: "olive oil",
          amount: 2,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "medium-butternut-squash-about-2-pounds-peeled-seeded-reserve-fibers-and-seeds-and-cut-into-1-2-inch-cubes-about-31-2-cups-see-note",
          displayName: "medium butternut squash (about 2 pounds), peeled, seeded (reserve fibers and seeds), and cut into 1/2-inch cubes (about 31/2 cups; see note)",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          allergens: [
            "TREE_NUT",
            "DAIRY"
          ]
        },
    {
          ingredientId: "table-salt",
          displayName: "table salt",
          amount: 0.75,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "ground-black-pepper",
          displayName: "ground black pepper",
          amount: 0.75,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "low-sodium-chicken-broth",
          displayName: "low-sodium chicken broth",
          amount: 4,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "FROZEN",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "water",
          displayName: "water",
          amount: 1,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "1-2-stick-unsalted-butter",
          displayName: "(1/2 stick) unsalted butter",
          amount: 4,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "small-onions-minced-about-11-2-cups",
          displayName: "small onions, minced (about 11/2 cups)",
          amount: 2,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "medium-garlic-cloves-minced-or-pressed-through-a-garlic-press-about-2-teaspoons",
          displayName: "medium garlic cloves, minced or pressed through a garlic press (about 2 teaspoons)",
          amount: 2,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "arborio-rice",
          displayName: "Arborio rice",
          amount: 2,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "CARB",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "dry-white-wine",
          displayName: "dry white wine",
          amount: 1.5,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "parmesan-cheese-grated-fine-about-3-4-cup",
          displayName: "Parmesan cheese, grated fine (about 3/4 cup)",
          amount: 1.5,
          unit: "OZ",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "minced-fresh-sage-leaves",
          displayName: "minced fresh sage leaves",
          amount: 2,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "grated-nutmeg",
          displayName: "grated nutmeg",
          amount: 0.25,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        }
  ],
  preflight: [],
  steps: [
    {
          stepNumber: 1,
          instruction: "Heat the oil in a 12-inch nonstick skillet over medium-high heat until shimmering but not smoking. Add the squash in an even layer and cook without stirring until golden brown, 4 to 5 minutes; stir in 1/4 teaspoon of the salt and 1/4 teaspoon of the pepper. Continue to cook, stirring occasionally, until the squash is tender and browned, about 5 minutes longer. Transfer the squash to a bowl and set aside."
        },
    {
          stepNumber: 2,
          instruction: "Return the skillet to medium heat; add the reserved squash fibers and seeds and any leftover diced squash. Cook, stirring frequently to break up the fibers, until lightly browned, about 4 minutes. Transfer to a large saucepan and add the chicken broth and water; cover the saucepan and bring the mixture to a simmer over high heat, then reduce the heat to medium-low to maintain a bare simmer."
        },
    {
          stepNumber: 3,
          instruction: "Melt 3 tablespoons of the butter in the now-empty skillet over medium heat; add the onions, garlic, remaining 1/2 teaspoon salt, and remaining 1/2 teaspoon pepper. Cook, stirring occasionally, until the onions are softened, 4 to 5 minutes. Add the rice to the skillet and cook, stirring frequently, until the grains are translucent around the edges, about 3 minutes. (To prevent the rice from spilling out of the pan, stir inward, from the edges of the pan toward the center, not in a circular motion.) Add the wine and cook, stirring frequently, until the liquid is fully absorbed, 4 to 5 minutes. Meanwhile, strain the hot broth through a fine-mesh strainer into a medium bowl, pressing on the solids to extract as much liquid as possible. Return the strained broth to the saucepan and discard the solids in the strainer; cover the saucepan and set over low heat to keep the broth hot."
        },
    {
          stepNumber: 4,
          instruction: "When the wine is fully absorbed, add 3 cups of the hot broth and half of the reserved squash to the rice. Simmer, stirring every 3 to 4 minutes, until the liquid is absorbed and the bottom of the pan is almost dry, about 12 minutes."
        },
    {
          stepNumber: 5,
          instruction: "Stir in 1/2 cup more of the hot broth and cook, stirring constantly, until absorbed, about 3 minutes; repeat with additional broth until the rice is cooked through but the grains are still somewhat firm at the center. Off the heat, stir in the remaining 1 tablespoon butter, the Parmesan, sage, and nutmeg; gently fold in the remaining cooked squash. If desired, add up to 1/4 cup more broth to loosen the texture of the risotto. Serve immediately in warmed bowls."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ],
  recipeAllergens: [
    "TREE_NUT",
    "DAIRY"
  ]
} satisfies Recipe;
