// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:18.064Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const cCtelDeCamarNMexicanShrimpCocktail = {
  id: "atk_c-ctel-de-camar-n-mexican-shrimp-cocktail",
  name: "Cóctel de Camarón (Mexican Shrimp Cocktail)",
  slug: "c-ctel-de-camar-n-mexican-shrimp-cocktail",
  metadata: {
    timeBand: "FAST",
    estimatedMinutes: 35,
    leftoverStrategy: "EXPECTED",
    baseServings: 5,
    yieldText: "SERVES 4 to 6",
    equipmentTags: []
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "large-shrimp-26-to-30-per-pound-peeled-deveined-and-tails-removed-see-this-page",
          displayName: "large shrimp (26 to 30 per pound), peeled, deveined, and tails removed (see this page)",
          amount: 1.25,
          unit: "LB",
          criticality: "CRITICAL",
          kind: "PROTEIN",
          shoppingCategory: "MEAT_SEAFOOD",
          quantityKind: "FIXED",
          allergens: [
            "SHELLFISH"
          ]
        },
    {
          ingredientId: "table-salt-plus-salt-for-cooking-shrimp",
          displayName: "table salt, plus salt for cooking shrimp",
          amount: 0.25,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          allergens: [
            "SHELLFISH"
          ]
        },
    {
          ingredientId: "v8-juice-chilled",
          displayName: "V8 juice, chilled",
          amount: 1,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          component: "SAUCE"
        },
    {
          ingredientId: "ketchup",
          displayName: "ketchup",
          amount: 0.5,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "SAUCE"
        },
    {
          ingredientId: "lime-juice-2-limes-plus-lime-wedges-for-serving",
          displayName: "lime juice (2 limes), plus lime wedges for serving",
          amount: 3,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "FRUIT",
          shoppingCategory: "PRODUCE",
          quantityKind: "APPROXIMATE",
          component: "SAUCE"
        },
    {
          ingredientId: "hot-sauce-plus-extra-for-serving",
          displayName: "hot sauce, plus extra for serving",
          amount: 2,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "TO_TASTE",
          component: "SAUCE"
        },
    {
          ingredientId: "english-cucumber-cut-into-1-2-inch-pieces",
          displayName: "English cucumber, cut into 1/2-inch pieces",
          amount: 0.5,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "finely-chopped-red-onion",
          displayName: "finely chopped red onion",
          amount: 1,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "avocado-halved-pitted-and-cut-into-1-2-inch-pieces",
          displayName: "avocado, halved, pitted, and cut into 1/2-inch pieces",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "FRUIT",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "chopped-fresh-cilantro",
          displayName: "chopped fresh cilantro",
          amount: 0.25,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          component: "GARNISH"
        },
    {
          ingredientId: "saltines",
          displayName: "Saltines",
          amount: 1,
          unit: "UNIT",
          criticality: "NON_CRITICAL",
          kind: "CARB",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        }
  ],
  preflight: [],
  steps: [
    {
          stepNumber: 1,
          instruction: "Bring 3 cups water to boil in large saucepan over high heat. Stir in shrimp and 1 tablespoon salt. Cover and let stand off heat until shrimp are opaque, about 5 minutes, shaking saucepan halfway through. Fill large bowl halfway with ice and water. Transfer shrimp to ice bath and let cool for 3 to 5 minutes. Once cool, cut each shrimp crosswise into 3 pieces."
        },
    {
          stepNumber: 2,
          instruction: "Combine V8 juice, ketchup, lime juice, hot sauce, and salt in medium bowl. Add cucumber, onion, and shrimp and stir until evenly coated. Stir in avocado and cilantro. Portion cocktail into individual bowls or glasses and serve immediately, passing saltines, lime wedges, and extra hot sauce separately."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ],
  recipeAllergens: [
    "SHELLFISH"
  ]
} satisfies Recipe;
