// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:18.643Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const cincinnatiChili = {
  id: "atk_cincinnati-chili",
  name: "Cincinnati Chili",
  slug: "cincinnati-chili",
  metadata: {
    timeBand: "NORMAL",
    estimatedMinutes: 90,
    leftoverStrategy: "EXPECTED",
    baseServings: 6,
    yieldText: "SERVES 6 to 8",
    equipmentTags: []
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "table-salt-plus-more-to-taste",
          displayName: "table salt, plus more to taste",
          amount: 2,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "80-percent-lean-ground-chuck",
          displayName: "80 percent lean ground chuck",
          amount: 1.5,
          unit: "LB",
          criticality: "CRITICAL",
          kind: "PROTEIN",
          shoppingCategory: "MEAT_SEAFOOD",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "vegetable-oil",
          displayName: "vegetable oil",
          amount: 2,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "medium-onions-minced",
          displayName: "medium onions, minced",
          amount: 2,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "medium-garlic-cloves-minced-or-pressed-through-a-garlic-press-about-2-teaspoons",
          displayName: "medium garlic cloves, minced or pressed through a garlic press (about 2 teaspoons)",
          amount: 2,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "chili-powder",
          displayName: "chili powder",
          amount: 2,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "dried-oregano",
          displayName: "dried oregano",
          amount: 2,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "cocoa-powder",
          displayName: "cocoa powder",
          amount: 2,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "ground-cinnamon",
          displayName: "ground cinnamon",
          amount: 1.5,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "cayenne-pepper",
          displayName: "cayenne pepper",
          amount: 0.5,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "ground-allspice",
          displayName: "ground allspice",
          amount: 0.5,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "ground-black-pepper",
          displayName: "ground black pepper",
          amount: 0.25,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "tomato-sauce",
          displayName: "tomato sauce",
          amount: 2,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "low-sodium-chicken-broth",
          displayName: "low-sodium chicken broth",
          amount: 2,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "water",
          displayName: "water",
          amount: 2,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "cider-vinegar",
          displayName: "cider vinegar",
          amount: 2,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "dark-brown-sugar",
          displayName: "dark brown sugar",
          amount: 2,
          unit: "TSP",
          criticality: "NON_CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "TO_TASTE"
        },
    {
          ingredientId: "hot-sauce",
          displayName: "Hot sauce",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "CARB",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "spaghetti-cooked-drained-and-tossed-with-2-tablespoons-unsalted-butter",
          displayName: "spaghetti, cooked, drained, and tossed with 2 tablespoons unsalted butter",
          amount: 1,
          unit: "LB",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          component: "GARNISH",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "sharp-cheddar-cheese-shredded-about-3-cups",
          displayName: "sharp cheddar cheese, shredded (about 3 cups)",
          amount: 12,
          unit: "OZ",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "GARNISH",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "can-red-kidney-beans-drained-rinsed-and-warmed",
          displayName: "can red kidney beans, drained, rinsed, and warmed",
          amount: 1,
          unit: "OZ",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          component: "GARNISH"
        },
    {
          ingredientId: "medium-onion-chopped",
          displayName: "medium onion, chopped",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        }
  ],
  preflight: [],
  steps: [
    {
          stepNumber: 1,
          instruction: "FOR THE CHILI: Bring 2 quarts water and 1 teaspoon of the salt to a boil in a large saucepan. Add the ground chuck, stirring vigorously to separate the meat into individual strands. As soon as the foam from the meat rises to the top (this takes about 30 seconds) and before the water returns to a boil, drain the meat into a strainer and set it aside."
        },
    {
          stepNumber: 2,
          instruction: "Rinse and dry the empty saucepan. Set the pan over medium heat and add the oil. When the oil is warm, add the onions and cook, stirring frequently, until the onions are soft and browned around the edges, about 8 minutes. Add the garlic and cook until fragrant, about 1 minute. Stir in the chili powder, oregano, cocoa, cinnamon, cayenne, allspice, black pepper, and the remaining 1 teaspoon salt. Cook, stirring constantly, until the spices are fragrant, about 30 seconds. Stir in the tomato sauce, broth, water, vinegar, and sugar, scraping the pan bottom to remove any browned bits."
        },
    {
          stepNumber: 3,
          instruction: "Add the blanched ground beef and increase the heat to high. As soon as the liquid boils, reduce the heat to medium-low and simmer, stirring occasionally, until the chili is deep red and has thickened slightly, about 1 hour. Season with salt and hot sauce to taste. (The chili can be refrigerated in an airtight container for up to 3 days. Bring to a simmer over medium-low heat before serving.)"
        },
    {
          stepNumber: 4,
          instruction: "TO SERVE: Divide the buttered spaghetti among individual bowls. Spoon the chili over the spaghetti and top with the cheese, beans, and onion. Serve immediately."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ],
  recipeAllergens: [
    "DAIRY"
  ]
} satisfies Recipe;
