// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:18.700Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const classicChickenSalad = {
  id: "atk_classic-chicken-salad",
  name: "Classic Chicken Salad",
  slug: "classic-chicken-salad",
  metadata: {
    timeBand: "NORMAL",
    estimatedMinutes: 60,
    equipmentTags: [
      "DUTCH_OVEN",
      "SHEET_PAN"
    ],
    leftoverStrategy: "EXPECTED",
    baseServings: 5,
    yieldText: "SERVES 4 to 6"
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "table-salt-for-cooking-chicken",
          displayName: "Table salt for cooking chicken",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "6-to-8-ounce-boneless-skinless-chicken-breasts-no-more-than-1-inch-thick-trimmed",
          displayName: "(6- to 8-ounce) boneless, skinless chicken breasts, no more than 1 inch thick, trimmed",
          amount: 4,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "PROTEIN",
          shoppingCategory: "MEAT_SEAFOOD",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "mayonnaise",
          displayName: "mayonnaise",
          amount: 0.5,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "APPROXIMATE",
          component: "DRESSING"
        },
    {
          ingredientId: "lemon-juice",
          displayName: "lemon juice",
          amount: 2,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "APPROXIMATE",
          component: "DRESSING"
        },
    {
          ingredientId: "dijon-mustard",
          displayName: "Dijon mustard",
          amount: 1,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "APPROXIMATE",
          component: "DRESSING"
        },
    {
          ingredientId: "pepper",
          displayName: "pepper",
          amount: 0.25,
          unit: "TSP",
          criticality: "NON_CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "APPROXIMATE",
          component: "DRESSING"
        },
    {
          ingredientId: "celery-ribs-minced",
          displayName: "celery ribs, minced",
          amount: 2,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "shallot-minced",
          displayName: "shallot, minced",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "minced-fresh-parsley",
          displayName: "minced fresh parsley",
          amount: 1,
          unit: "TBSP",
          criticality: "NON_CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PRODUCE",
          quantityKind: "APPROXIMATE",
          component: "GARNISH"
        },
    {
          ingredientId: "minced-fresh-tarragon",
          displayName: "minced fresh tarragon",
          amount: 1,
          unit: "TBSP",
          criticality: "NON_CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PRODUCE",
          quantityKind: "APPROXIMATE",
          component: "GARNISH"
        }
  ],
  preflight: [
    {
          description: "Cool chicken to room temperature, then refrigerate to fully chill, approximately 30 minutes.",
          kind: "LONG_PREP",
          hoursBefore: 1,
          type: "LONG_PREP"
        }
  ],
  steps: [
    {
          stepNumber: 1,
          instruction: "Dissolve 2 tablespoons salt in 6 cups cold water in Dutch oven. Submerge chicken in water. Heat pot over medium heat until water registers 170 degrees. Turn off heat, cover pot, and let stand until chicken registers 165 degrees, 15 to 17 minutes."
        },
    {
          stepNumber: 2,
          instruction: "Transfer chicken to paper towel–lined baking sheet. Refrigerate until chicken is cool, about 30 minutes. While chicken cools, whisk mayonnaise, lemon juice, mustard, and pepper together in large bowl."
        },
    {
          stepNumber: 3,
          instruction: "Pat chicken dry with paper towels and cut into 1/2-inch pieces. Transfer chicken to bowl with mayonnaise mixture. Add celery, shallot, parsley, and tarragon; toss to combine. Season with salt and pepper to taste. Serve. (Salad can be refrigerated for up to 2 days.)"
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ]
} satisfies Recipe;
