// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:19.285Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const darkChocolateFudgeSauce = {
  id: "atk_dark-chocolate-fudge-sauce",
  name: "Dark Chocolate Fudge Sauce",
  slug: "dark-chocolate-fudge-sauce",
  metadata: {
    timeBand: "FAST",
    estimatedMinutes: 20,
    leftoverStrategy: "EXPECTED",
    yieldText: "MAKES 2 cups",
    baseServings: 8,
    equipmentTags: []
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "sugar",
          displayName: "sugar",
          amount: 1.25,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "CARB",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "whole-or-2-percent-low-fat-milk",
          displayName: "whole or 2 percent low-fat milk",
          amount: 0.6666666666666666,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "table-salt",
          displayName: "table salt",
          amount: 0.25,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "unsweetened-cocoa-powder-sifted",
          displayName: "unsweetened cocoa powder, sifted",
          amount: 0.3333333333333333,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "unsweetened-chocolate-chopped-fine",
          displayName: "unsweetened chocolate, chopped fine",
          amount: 3,
          unit: "OZ",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "unsalted-butter-cut-into-8-pieces-and-chilled",
          displayName: "unsalted butter, cut into 8 pieces and chilled",
          amount: 4,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "vanilla-extract",
          displayName: "vanilla extract",
          amount: 1,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        }
  ],
  preflight: [],
  steps: [
    {
          stepNumber: 1,
          instruction: "Heat sugar, milk, and salt in medium saucepan over medium-low heat, whisking gently, until sugar has dissolved and liquid starts to bubble around edges of saucepan, 5 to 6 minutes. Reduce heat to low, add cocoa, and whisk until smooth."
        },
    {
          stepNumber: 2,
          instruction: "Remove saucepan from heat, stir in chocolate, and let stand for 3 minutes. Whisk sauce until smooth and chocolate is fully melted. Add butter and whisk until fully incorporated and sauce thickens slightly. Whisk in vanilla and serve. (Sauce can be refrigerated in airtight container for up to 1 month. Gently reheat sauce in microwave [do not let it exceed 110 degrees], stirring every 10 seconds, until just warmed and pourable.)"
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ],
  recipeAllergens: [
    "DAIRY"
  ]
} satisfies Recipe;
