// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:19.767Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const freshCornCornbread = {
  id: "atk_fresh-corn-cornbread",
  name: "Fresh Corn Cornbread",
  slug: "fresh-corn-cornbread",
  metadata: {
    timeBand: "NORMAL",
    estimatedMinutes: 60,
    equipmentTags: [
      "OVEN",
      "LARGE_SKILLET",
      "BLENDER"
    ],
    leftoverStrategy: "EXPECTED",
    baseServings: 6,
    yieldText: "SERVES 6 to 8"
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "62-3-ounces-stone-ground-cornmeal",
          displayName: "(62/3 ounces) stone-ground cornmeal",
          amount: 1.3333333333333333,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "CARB",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "5-ounces-all-purpose-flour",
          displayName: "(5 ounces) all-purpose flour",
          amount: 1,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "CARB",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "sugar",
          displayName: "sugar",
          amount: 2,
          unit: "TBSP",
          criticality: "NON_CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "baking-powder",
          displayName: "baking powder",
          amount: 1.5,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "baking-soda",
          displayName: "baking soda",
          amount: 0.25,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "table-salt",
          displayName: "table salt",
          amount: 1.25,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "ears-corn-kernels-cut-from-cobs-21-4-cups",
          displayName: "ears corn, kernels cut from cobs (21/4 cups)",
          amount: 3,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "unsalted-butter-cut-into-6-pieces",
          displayName: "unsalted butter, cut into 6 pieces",
          amount: 6,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "buttermilk",
          displayName: "buttermilk",
          amount: 1,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "large-eggs-plus-1-large-yolk",
          displayName: "large eggs plus 1 large yolk",
          amount: 2,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED"
        }
  ],
  preflight: [],
  steps: [
    {
          stepNumber: 1,
          instruction: "Adjust oven rack to middle position and heat oven to 400 degrees. Whisk cornmeal, flour, sugar, baking powder, baking soda, and salt together in large bowl."
        },
    {
          stepNumber: 2,
          instruction: "Process corn kernels in blender until very smooth, about 2 minutes. Transfer puree to medium saucepan (you should have about 11/2 cups). Cook puree over medium heat, stirring constantly, until very thick and deep yellow and it measures 3/4 cup, 5 to 8 minutes."
        },
    {
          stepNumber: 3,
          instruction: "Remove pan from heat. Add 5 tablespoons butter and whisk until melted and incorporated. Add buttermilk and whisk until incorporated. Add eggs and yolk and whisk until incorporated. Transfer corn mixture to bowl with cornmeal mixture and, using rubber spatula, fold together until just combined."
        },
    {
          stepNumber: 4,
          instruction: "Melt remaining 1 tablespoon butter in 10-inch cast-iron skillet over medium heat. Scrape batter into skillet and spread into even layer. Bake until top is golden brown and toothpick inserted in center comes out clean, 23 to 28 minutes. Let cool on wire rack for 5 minutes. Remove cornbread from skillet and let cool for 20 minutes before cutting into wedges and serving."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ],
  recipeAllergens: [
    "DAIRY"
  ]
} satisfies Recipe;
