// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:20.076Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const gougRes = {
  id: "atk_goug-res",
  name: "Gougères",
  slug: "goug-res",
  metadata: {
    timeBand: "NORMAL",
    estimatedMinutes: 60,
    equipmentTags: [
      "OVEN",
      "SHEET_PAN",
      "FOOD_PROCESSOR"
    ],
    leftoverStrategy: "EXPECTED",
    yieldText: "MAKES 24 puffs SEASON 26",
    baseServings: 24
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "large-eggs-plus-1-large-white",
          displayName: "large eggs plus 1 large white",
          amount: 2,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "salt",
          displayName: "salt",
          amount: 0.25,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "water",
          displayName: "water",
          amount: 0.5,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "unsalted-butter-cut-into-4-pieces",
          displayName: "unsalted butter, cut into 4 pieces",
          amount: 2,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "pinch-cayenne-pepper",
          displayName: "Pinch cayenne pepper",
          amount: 1,
          unit: "UNIT",
          criticality: "NON_CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "21-2-ounces-all-purpose-flour",
          displayName: "(21/2 ounces) all-purpose flour",
          amount: 0.5,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "CARB",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "gruy-re-cheese-shredded-1-cup",
          displayName: "Gruyère cheese, shredded (1 cup)",
          amount: 4,
          unit: "OZ",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        }
  ],
  preflight: [],
  steps: [
    {
          stepNumber: 1,
          instruction: "Adjust oven rack to upper-middle position and heat oven to 425 degrees. Line rimmed baking sheet with parchment paper and nest it in second rimmed baking sheet. In 2-cup liquid measuring cup, beat eggs and white and salt until well combined. (You should have about 1/2 cup egg mixture. Discard excess.) Set aside."
        },
    {
          stepNumber: 2,
          instruction: "Heat water, butter, and cayenne in small saucepan over medium heat. When mixture begins to simmer, reduce heat to low and immediately stir in flour using wooden spoon. Cook, stirring constantly, using smearing motion, until mixture is very thick, forms ball, and pulls away from sides of saucepan, about 30 seconds."
        },
    {
          stepNumber: 3,
          instruction: "Immediately transfer mixture to food processor and process with feed tube open for 5 seconds to cool slightly. With processor running, gradually add reserved egg mixture in steady stream, then scrape down sides of bowl and add Gruyère. Process until paste is very glossy and flecked with coarse cornmeal–size pieces of cheese, 30 to 40 seconds. (If not using immediately, transfer paste to bowl, press sheet of greased parchment directly on surface, and store at room temperature for up to 2 hours.)"
        },
    {
          stepNumber: 4,
          instruction: "Scoop 1 level tablespoon of dough. Using second small spoon, scrape dough onto prepared sheet into 11/2-inch-wide, 1-inch-tall mound. Repeat, spacing mounds 1 to 11/4 inches apart. (You should have 24 mounds.) Using back of spoon lightly coated with vegetable oil spray, smooth away any creases and large peaks on each mound."
        },
    {
          stepNumber: 5,
          instruction: "Bake until gougères are puffed and upper two-thirds of each are light golden brown (bottom third will still be pale), 14 to 20 minutes. Turn off oven; leave gougères in oven until uniformly golden brown, 10 to 15 minutes (do not open oven for at least 8 minutes). Transfer gougères to wire rack and let cool for 15 minutes. Serve warm."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ],
  recipeAllergens: [
    "DAIRY"
  ]
} satisfies Recipe;
