// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:20.643Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const grilledTomatoAndCheesePizza = {
  id: "atk_grilled-tomato-and-cheese-pizza",
  name: "Grilled Tomato and Cheese Pizza",
  slug: "grilled-tomato-and-cheese-pizza",
  metadata: {
    timeBand: "NORMAL",
    estimatedMinutes: 180,
    equipmentTags: [
      "GRILL",
      "FOOD_PROCESSOR"
    ],
    leftoverStrategy: "EXPECTED",
    yieldText: "MAKES four 9-inch pizzas, serving 4 to 6",
    baseServings: 4
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "water-room-temperature",
          displayName: "water, room temperature",
          amount: 1,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "olive-oil",
          displayName: "olive oil",
          amount: 2,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "11-ounces-bread-flour",
          displayName: "(11 ounces) bread flour",
          amount: 2,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "CARB",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "DOUGH"
        },
    {
          ingredientId: "whole-wheat-flour-optional",
          displayName: "whole-wheat flour (optional)",
          amount: 1,
          unit: "TBSP",
          criticality: "NON_CRITICAL",
          kind: "CARB",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "DOUGH",
          allergens: [
            "WHEAT"
          ]
        },
    {
          ingredientId: "sugar",
          displayName: "sugar",
          amount: 2,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "DOUGH"
        },
    {
          ingredientId: "table-salt",
          displayName: "table salt",
          amount: 1.25,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "DOUGH"
        },
    {
          ingredientId: "instant-or-rapid-rise-yeast",
          displayName: "instant or rapid-rise yeast",
          amount: 1,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "DOUGH"
        },
    {
          ingredientId: "plum-tomatoes-cored-seeded-and-cut-into-1-2-inch-pieces",
          displayName: "plum tomatoes, cored, seeded, and cut into 1/2-inch pieces",
          amount: 1.5,
          unit: "LB",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          component: "TOPPING"
        },
    {
          ingredientId: "table-salt",
          displayName: "table salt",
          amount: 0.75,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "TOPPING"
        },
    {
          ingredientId: "fontina-cheese-shredded-11-2-cups",
          displayName: "fontina cheese, shredded (11/2 cups)",
          amount: 6,
          unit: "OZ",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          component: "TOPPING",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "parmesan-cheese-grated-fine-3-4-cup",
          displayName: "Parmesan cheese, grated fine (3/4 cup)",
          amount: 1.5,
          unit: "OZ",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          component: "TOPPING",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "recipe-spicy-garlic-oil-recipe-follows",
          displayName: "recipe Spicy Garlic Oil (recipe follows)",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "TOPPING"
        },
    {
          ingredientId: "chopped-fresh-basil",
          displayName: "chopped fresh basil",
          amount: 0.5,
          unit: "CUP",
          criticality: "NON_CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          component: "TOPPING"
        },
    {
          ingredientId: "kosher-salt",
          displayName: "Kosher salt",
          amount: 1,
          unit: "UNIT",
          criticality: "NON_CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "TO_TASTE",
          component: "TOPPING"
        }
  ],
  preflight: [
    {
          description: "Prepare dough",
          timeMinutes: 150,
          requirementKind: "LONG_PREP",
          type: "LONG_PREP"
        },
    {
          description: "Drain tomatoes",
          timeMinutes: 30,
          requirementKind: "LONG_PREP",
          type: "LONG_PREP"
        }
  ],
  steps: [
    {
          stepNumber: 1,
          instruction: "FOR THE DOUGH: Combine water and 2 tablespoons oil in liquid measuring cup. Pulse 13/4 cup bread flour, whole wheat flour, if using, sugar, salt, and yeast in food processor (fitted with dough blade if possible) until combined, about 5 pulses. With food processor running, slowly add water mixture; process until dough forms ball, about 11/2 minutes. (If after 11/2 minutes dough is sticky and clings to blade, add remaining 1/4 cup flour 1 tablespoon at a time.) Transfer dough to large, lightly greased bowl; cover tightly with plastic wrap and let rise at room temperature until doubled in size, 11/2 to 2 hours."
        },
    {
          stepNumber: 2,
          instruction: "Gently press down on center of dough to deflate. Transfer dough to clean counter and divide into 4 equal pieces. With cupped palms, form each piece into smooth, tight ball. Set dough balls on well-floured counter. Press dough rounds by hand to flatten; cover loosely with plastic and let rest for 15 minutes."
        },
    {
          stepNumber: 3,
          instruction: "FOR THE TOPPING: Meanwhile, toss tomatoes and salt in bowl; transfer to colander and drain for 30 minutes (wipe out and reserve bowl). Shake colander to drain off excess liquid; transfer tomatoes to now-empty bowl and set aside. Combine fontina and Parmesan in second bowl and set aside."
        },
    {
          stepNumber: 4,
          instruction: "Gently stretch 1 dough round (keep other rounds covered) into disk about 1/2 inch thick and 5 to 6 inches in diameter. Roll disk out to 1/8-inch thickness, 9 to 10 inches in diameter, on well-floured sheet of parchment paper, dusting with additional flour as needed to prevent sticking. (If dough shrinks when rolled out, cover with plastic and let rest until relaxed, 10 to 15 minutes.) Dust surface of rolled dough with flour and set aside. Repeat with remaining dough rounds, stacking sheets of rolled dough on top of each other (with parchment in between) and covering stack with plastic; set aside until grill is ready."
        },
    {
          stepNumber: 5,
          instruction: "Clean and oil cooking grate. Lightly flour pizza peel or baking sheet; invert 1 dough round onto peel, gently stretching it as needed to retain its shape (do not stretch dough too thin; thin spots will burn quickly). Peel off and discard parchment; carefully slide round onto hotter side of grill. Immediately repeat with another dough round. Cook (covered if using gas) until tops are covered with bubbles (pierce larger bubbles with paring knife) and bottoms are grill-marked and charred in spots, 1 to 4 minutes; while rounds cook, check undersides and slide to cooler area of grill if browning too quickly. Transfer crusts to cutting board, browned sides up. Repeat with 2 remaining dough rounds."
        },
    {
          stepNumber: 6,
          instruction: "Brush 2 crusts generously with garlic oil; top each evenly with one-quarter of cheese mixture and one-quarter of tomatoes. Return pizzas to hotter side of grill and cover grill with lid; cook until bottoms are well browned and cheese is melted, 2 to 6 minutes, checking bottoms frequently to prevent burning. Transfer pizzas to cutting board; repeat with remaining 2 crusts. Sprinkle pizzas with basil and season with salt to taste; cut into wedges and serve."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ],
  recipeAllergens: [
    "WHEAT",
    "DAIRY"
  ]
} satisfies Recipe;
