// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:20.423Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const grilledGlazedBonelessSkinlessChickenBreasts = {
  id: "atk_grilled-glazed-boneless-skinless-chicken-breasts",
  name: "Grilled Glazed Boneless, Skinless Chicken Breasts",
  slug: "grilled-glazed-boneless-skinless-chicken-breasts",
  metadata: {
    timeBand: "NORMAL",
    estimatedMinutes: 60,
    equipmentTags: [
      "GRILL"
    ],
    leftoverStrategy: "EXPECTED",
    baseServings: 4,
    yieldText: "SERVES 4"
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "table-salt",
          displayName: "table salt",
          amount: 0.25,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "sugar",
          displayName: "sugar",
          amount: 0.25,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "6-to-8-ounce-boneless-skinless-chicken-breasts-trimmed",
          displayName: "(6- to 8-ounce) boneless, skinless chicken breasts, trimmed",
          amount: 4,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "PROTEIN",
          shoppingCategory: "MEAT_SEAFOOD",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "nonfat-dry-milk-powder",
          displayName: "nonfat dry milk powder",
          amount: 2,
          unit: "TSP",
          criticality: "NON_CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "pepper",
          displayName: "pepper",
          amount: 0.25,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "vegetable-oil-spray",
          displayName: "Vegetable oil spray",
          amount: 1,
          unit: "UNIT",
          criticality: "NON_CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "recipe-spicy-hoisin-glaze",
          displayName: "recipe Spicy Hoisin Glaze",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "OTHER",
          quantityKind: "FIXED",
          component: "GLAZE"
        }
  ],
  preflight: [
    {
          description: "Brine chicken breasts",
          durationMinutes: 60,
          priority: 1,
          type: "MARINATE"
        }
  ],
  steps: [
    {
          stepNumber: 1,
          instruction: "Dissolve salt and sugar in 11/2 quarts cold water. Submerge chicken in brine, cover, and refrigerate for at least 30 minutes or up to 1 hour. Remove chicken from brine and pat dry with paper towels. Combine milk powder and pepper in bowl."
        },
    {
          stepNumber: 2,
          instruction: "Clean and oil cooking grate. Sprinkle half of milk powder mixture over 1 side of chicken. Lightly spray coated side of chicken with oil spray until milk powder is moistened. Flip chicken and sprinkle remaining milk powder mixture over second side. Lightly spray with oil spray."
        },
    {
          stepNumber: 3,
          instruction: "Place chicken, skinned side down, on hotter side of grill and cook until browned on first side, 2 to 21/2 minutes. Flip chicken, brush with 2 tablespoons glaze, and cook until browned on second side, 2 to 21/2 minutes. Flip chicken, move to cooler side of grill, brush with 2 tablespoons glaze, and cook for 2 minutes. Repeat flipping and brushing 2 more times, cooking for 2 minutes on each side. Flip chicken, brush with remaining glaze, and cook until chicken registers 160 degrees, 1 to 3 minutes. Transfer chicken to plate and let rest for 5 minutes before serving."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ],
  recipeAllergens: [
    "DAIRY"
  ]
} satisfies Recipe;
