// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:20.923Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const honeydewSaladWithPeanutsAndLime = {
  id: "atk_honeydew-salad-with-peanuts-and-lime",
  name: "Honeydew Salad with Peanuts and Lime",
  slug: "honeydew-salad-with-peanuts-and-lime",
  metadata: {
    timeBand: "FAST",
    estimatedMinutes: 20,
    leftoverStrategy: "EXPECTED",
    baseServings: 5,
    yieldText: "SERVES 4 to 6",
    equipmentTags: []
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "taste-your-melon-as-you-cut-it-up-if-it-s-very-sweet-omit-the-sugar-if-it-s-less-sweet-add-the-sugar-to-the-dressing-this-salad-makes-a-light-and-refreshing-accompaniment-to-grilled-meat-or-fish-and-steamed-white-rice",
          displayName: "Taste your melon as you cut it up: If it’s very sweet, omit the sugar; if it’s less sweet, add the sugar to the dressing. This salad makes a light and refreshing accompaniment to grilled meat or fish and steamed white rice.",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "lime-juice-3-limes",
          displayName: "lime juice (3 limes)",
          amount: 0.3333333333333333,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "FRUIT",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          component: "DRESSING"
        },
    {
          ingredientId: "shallot-sliced-thin",
          displayName: "shallot, sliced thin",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          component: "DRESSING"
        },
    {
          ingredientId: "thai-chiles-stemmed-seeded-and-minced",
          displayName: "Thai chiles, stemmed, seeded, and minced",
          amount: 2,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          component: "DRESSING"
        },
    {
          ingredientId: "clove-minced",
          displayName: "clove, minced",
          amount: 1,
          unit: "GRAM",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "DRESSING"
        },
    {
          ingredientId: "table-salt",
          displayName: "table salt",
          amount: 0.5,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "DRESSING"
        },
    {
          ingredientId: "sugar-optional",
          displayName: "sugar (optional)",
          amount: 12,
          unit: "TBSP",
          criticality: "NON_CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "TO_TASTE",
          component: "DRESSING"
        },
    {
          ingredientId: "fish-sauce",
          displayName: "fish sauce",
          amount: 1,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "DRESSING",
          allergens: [
            "FISH"
          ]
        },
    {
          ingredientId: "honeydew-melon-peeled-halved-seeded-and-cut-into-11-2-inch-chunks-6-cups",
          displayName: "honeydew melon, peeled, halved, seeded, and cut into 11/2-inch chunks (6 cups)",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "FRUIT",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "chopped-fresh-cilantro-divided",
          displayName: "chopped fresh cilantro, divided",
          amount: 5,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          component: "GARNISH"
        },
    {
          ingredientId: "chopped-fresh-mint-divided",
          displayName: "chopped fresh mint, divided",
          amount: 5,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          component: "GARNISH"
        },
    {
          ingredientId: "salted-dry-roasted-peanuts-chopped-fine-divided",
          displayName: "salted dry-roasted peanuts, chopped fine, divided",
          amount: 5,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "GARNISH",
          allergens: [
            "PEANUT"
          ]
        }
  ],
  preflight: [],
  steps: [
    {
          stepNumber: 1,
          instruction: "Combine lime juice and shallot in large bowl. Using mortar and pestle (or on cutting board using flat side of chef’s knife), mash Thai chiles, garlic, and salt to fine paste. Add chile paste; sugar, if using; and fish sauce to lime juice mixture and stir to combine."
        },
    {
          stepNumber: 2,
          instruction: "Add honeydew, 1/4 cup cilantro, 1/4 cup mint, and 1/4 cup peanuts and toss to combine. Transfer to shallow serving bowl. Sprinkle with remaining 1 tablespoon cilantro, remaining 1 tablespoon mint, and remaining 1 tablespoon peanuts and serve."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ],
  recipeAllergens: [
    "FISH",
    "PEANUT"
  ]
} satisfies Recipe;
