// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:21.165Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const juliaChildSStuffedTurkeyUpdated = {
  id: "atk_julia-child-s-stuffed-turkey-updated",
  name: "Julia Child’s Stuffed Turkey, Updated",
  slug: "julia-child-s-stuffed-turkey-updated",
  metadata: {
    timeBand: "PROJECT",
    estimatedMinutes: 300,
    equipmentTags: [
      "OVEN",
      "LARGE_SKILLET"
    ],
    leftoverStrategy: "EXPECTED",
    baseServings: 11,
    yieldText: "SERVES 10 to 12"
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "12-to-15-pound-turkey-neck-and-giblets-removed-and-reserved-for-gravy",
          displayName: "(12- to 15-pound) turkey, neck and giblets removed and reserved for gravy",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "PROTEIN",
          shoppingCategory: "MEAT_SEAFOOD",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "plus-2-tablespoons-minced-fresh-sage",
          displayName: "plus 2 tablespoons minced fresh sage",
          amount: 1,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "table-salt-and-pepper",
          displayName: "Table salt and pepper",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "TO_TASTE"
        },
    {
          ingredientId: "wooden-skewers",
          displayName: "Wooden skewers",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "OTHER",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "hearty-white-sandwich-bread-cut-into-1-2-inch-cubes",
          displayName: "hearty white sandwich bread, cut into 1/2-inch cubes",
          amount: 1.5,
          unit: "LB",
          criticality: "CRITICAL",
          kind: "CARB",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "STUFFING"
        },
    {
          ingredientId: "vegetable-oil",
          displayName: "vegetable oil",
          amount: 1,
          unit: "TBSP",
          criticality: "NON_CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "unsalted-butter",
          displayName: "unsalted butter",
          amount: 3,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          component: "STUFFING",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "onions-chopped-fine",
          displayName: "onions, chopped fine",
          amount: 3,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          component: "STUFFING"
        },
    {
          ingredientId: "celery-ribs-minced",
          displayName: "celery ribs, minced",
          amount: 6,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          component: "STUFFING"
        },
    {
          ingredientId: "dried-cranberries",
          displayName: "dried cranberries",
          amount: 1,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "FRUIT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "STUFFING"
        },
    {
          ingredientId: "large-eggs-beaten",
          displayName: "large eggs, beaten",
          amount: 4,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          component: "STUFFING"
        }
  ],
  preflight: [
    {
          durationMinutes: 360,
          description: "Refrigerate leg quarters for 6 to 12 hours.",
          kind: "MARINATE",
          type: "LONG_PREP"
        },
    {
          durationMinutes: 360,
          description: "Brine breast for 6 to 12 hours.",
          kind: "MARINATE",
          type: "LONG_PREP"
        }
  ],
  steps: [
    {
          stepNumber: 1,
          instruction: "With turkey breast side up, using boning or paring knife, cut through skin around leg quarter where it attaches to breast. Bend leg back to pop leg bone out of socket. Cut through joint to separate leg quarter. Repeat to remove second leg quarter. Working with 1 leg quarter at a time and with skin side down, use tip of knife to cut along sides of thighbone to expose bone, then slide knife under bone to free meat. Cut joint between thigh and leg and remove thighbone. Reserve thighbones for gravy."
        },
    {
          stepNumber: 2,
          instruction: "Rub interior of each thigh with 1/2 teaspoon sage, 1/2 teaspoon salt, and 1/4 teaspoon pepper. Truss each thigh closed using wooden skewers and kitchen twine. Place leg quarters on large plate, cover, and refrigerate for 6 to 12 hours."
        },
    {
          stepNumber: 3,
          instruction: "Using kitchen shears, cut through ribs following vertical line of fat where breast meets back from tapered end of breast to wing joint. Using your hands, bend back away from breast to pop shoulder joint out of socket. Cut through joint between bones to separate back from breast. Reserve back for gravy. Trim excess fat from breast. Dissolve 3/4 cup salt in 6 quarts cold water in large container. Submerge breast in brine, cover, and refrigerate for 6 to 12 hours."
        },
    {
          stepNumber: 4,
          instruction: "Adjust oven racks to upper-middle and lower-middle positions and heat oven to 300 degrees. Spread bread cubes in even layer on 2 rimmed baking sheets and bake until mostly dry and very lightly browned, 25 to 30 minutes, stirring occasionally during baking. Transfer dried bread to large bowl. Increase oven temperature to 425 degrees."
        },
    {
          stepNumber: 5,
          instruction: "While bread dries, remove breast from brine and pat dry with paper towels (leave leg quarters in refrigerator). Tuck wings behind back. Brush surface with 2 teaspoons oil. Melt butter in 12-inch nonstick ovensafe skillet over medium heat. Add onions and cook, stirring occasionally, until softened, 10 to 12 minutes. Add celery, remaining 2 tablespoons sage, and 11/2 teaspoons pepper; continue to cook until celery is slightly softened, 3 to 5 minutes longer. Transfer vegetables to bowl with bread and wipe out skillet with paper towels. Place turkey breast skin side down in skillet, and roast in oven for 30 minutes."
        },
    {
          stepNumber: 6,
          instruction: "While breast roasts, add cranberries and eggs to bread mixture and toss to combine (mixture will be dry). Transfer stuffing to 16 by 13-inch roasting pan and, using rubber spatula, pat stuffing into level 12 by 10-inch rectangle."
        },
    {
          stepNumber: 7,
          instruction: "Remove breast from oven, and using 2 wads of paper towels, flip breast and place over two-thirds of stuffing. Arrange leg quarters over remaining stuffing and brush with remaining 1 teaspoon oil. Lightly season breast and leg quarters with salt. Tuck any large sections of exposed stuffing under bird so most of stuffing is covered by turkey. Transfer pan to oven and cook for 30 minutes."
        },
    {
          stepNumber: 8,
          instruction: "Reduce oven temperature to 350 degrees. Continue to roast until thickest part of breast registers 160 degrees and thickest part of thigh registers 175 degrees, 40 minutes to 1 hour 20 minutes longer. Transfer breast and leg quarters to cutting board and let rest for 30 minutes. While turkey rests, using metal spatula, stir stuffing well, scraping up any browned bits. Redistribute stuffing over bottom of roasting pan, return to oven, and turn off oven."
        },
    {
          stepNumber: 9,
          instruction: "Before serving, season stuffing with salt and pepper to taste. Mound stuffing in center of platter. Place breast on top of stuffing with point of breast resting on highest part of mound. Remove skewers and twine from leg quarters and place on each side of breast. Carve and serve."
        },
    {
          stepNumber: 10,
          instruction: "Using boning or paring knife, cut through skin around leg where it attaches to breast. Bend leg back to pop leg bone out of socket. Cut through joint to separate leg quarter."
        },
    {
          stepNumber: 11,
          instruction: "With tip of knife, cut along sides of thighbone to expose bone, then slide knife under bone to free meat. Without severing skin, cut joint between thigh and leg and remove thighbone."
        },
    {
          stepNumber: 12,
          instruction: "Rub interior of each thigh with sage, salt, and pepper. Truss thighs closed with wooden skewers and kitchen twine."
        },
    {
          stepNumber: 13,
          instruction: "Using kitchen shears, cut through ribs, following line of fat running from tapered end of breast to wing joint."
        },
    {
          stepNumber: 14,
          instruction: "Using your hands, bend backbone away from breast to pop shoulder joint out of socket."
        },
    {
          stepNumber: 15,
          instruction: "Cut through shoulder joint to separate back from breast."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ],
  recipeAllergens: [
    "DAIRY"
  ]
} satisfies Recipe;
