// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:21.351Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const lemonPossetWithBerries = {
  id: "atk_lemon-posset-with-berries",
  name: "Lemon Posset with Berries",
  slug: "lemon-posset-with-berries",
  metadata: {
    timeBand: "PROJECT",
    estimatedMinutes: 360,
    leftoverStrategy: "EXPECTED",
    baseServings: 6,
    yieldText: "SERVES 6",
    equipmentTags: []
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "heavy-cream",
          displayName: "heavy cream",
          amount: 2,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "42-3-ounces-sugar",
          displayName: "(42/3 ounces) sugar",
          amount: 0.6666666666666666,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "CARB",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "grated-lemon-zest-plus-6-tablespoons-juice-2-lemons",
          displayName: "grated lemon zest plus 6 tablespoons juice (2 lemons)",
          amount: 1,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "FRUIT",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "71-2-ounces-blueberries-or-raspberries",
          displayName: "(71/2 ounces) blueberries or raspberries",
          amount: 1.5,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "FRUIT",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          component: "GARNISH"
        }
  ],
  preflight: [
    {
          description: "Refrigerate uncovered for at least 3 hours, or up to 2 days wrapped.",
          durationMinutes: 180,
          kind: "CHILL",
          type: "LONG_PREP"
        }
  ],
  steps: [
    {
          stepNumber: 1,
          instruction: "Combine cream, sugar, and lemon zest in medium saucepan and bring to boil over medium heat. Continue to boil, stirring frequently to dissolve sugar. If mixture begins to boil over, briefly remove from heat. Cook until mixture is reduced to 2 cups, 8 to 12 minutes."
        },
    {
          stepNumber: 2,
          instruction: "Remove saucepan from heat and stir in lemon juice. Let sit until mixture is cooled slightly and skin forms on top, about 20 minutes. Strain through fine-mesh strainer into bowl; discard zest. Divide mixture evenly among 6 individual ramekins or serving glasses."
        },
    {
          stepNumber: 3,
          instruction: "Refrigerate, uncovered, until set, at least 3 hours. (Once chilled, possets can be wrapped in plastic wrap and refrigerated for up to 2 days. Unwrap and let sit at room temperature for 10 minutes before serving.) Garnish with berries and serve."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ],
  recipeAllergens: [
    "DAIRY"
  ]
} satisfies Recipe;
