// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:21.822Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const mustardyAppleButterGlazedPorkChops = {
  id: "atk_mustardy-apple-butter-glazed-pork-chops",
  name: "Mustardy Apple Butter–Glazed Pork Chops",
  slug: "mustardy-apple-butter-glazed-pork-chops",
  metadata: {
    timeBand: "NORMAL",
    estimatedMinutes: 60,
    equipmentTags: [
      "OVEN",
      "SHEET_PAN"
    ],
    leftoverStrategy: "EXPECTED",
    baseServings: 4,
    yieldText: "SERVES 4"
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "apple-butter",
          displayName: "apple butter",
          amount: 3,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "FRUIT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "maple-syrup",
          displayName: "maple syrup",
          amount: 2,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "dijon-mustard",
          displayName: "Dijon mustard",
          amount: 1,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "soy-sauce",
          displayName: "soy sauce",
          amount: 1,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          allergens: [
            "SOY"
          ]
        },
    {
          ingredientId: "cider-vinegar",
          displayName: "cider vinegar",
          amount: 0.5,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "kosher-salt",
          displayName: "kosher salt",
          amount: 1,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "6-to-8-ounce-boneless-pork-chops-3-4-to-1-inch-thick-trimmed",
          displayName: "(6- to 8-ounce) boneless pork chops, 3/4 to 1 inch thick, trimmed",
          amount: 4,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "PROTEIN",
          shoppingCategory: "MEAT_SEAFOOD",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "minced-fresh-parsley",
          displayName: "minced fresh parsley",
          amount: 2,
          unit: "TSP",
          criticality: "NON_CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          optional: true
        }
  ],
  preflight: [],
  steps: [
    {
          stepNumber: 1,
          instruction: "Adjust oven rack to middle position and heat oven to 275 degrees. Line rimmed baking sheet with aluminum foil and set wire rack in sheet. Spray rack with vegetable oil spray. Stir apple butter, maple syrup, mustard, soy sauce, and vinegar together in small bowl."
        },
    {
          stepNumber: 2,
          instruction: "Sprinkle salt evenly over both sides of chops. Place chops on prepared wire rack and brush 1 teaspoon glaze on top and sides of each chop. Roast until meat registers 135 to 137 degrees, 40 to 45 minutes."
        },
    {
          stepNumber: 3,
          instruction: "Remove sheet from oven and heat broiler. Brush 1 tablespoon glaze on top and sides of each chop. Return sheet to oven and broil until glaze is bubbly and slightly charred in spots, 3 to 6 minutes. Let rest for 5 minutes. Sprinkle with parsley and serve."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ],
  recipeAllergens: [
    "DAIRY",
    "SOY"
  ]
} satisfies Recipe;
