// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:22.293Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const panSearedOvenRoastedPorkTenderloin = {
  id: "atk_pan-seared-oven-roasted-pork-tenderloin",
  name: "Pan-Seared Oven-Roasted Pork Tenderloin",
  slug: "pan-seared-oven-roasted-pork-tenderloin",
  metadata: {
    timeBand: "NORMAL",
    estimatedMinutes: 45,
    equipmentTags: [
      "OVEN",
      "LARGE_SKILLET"
    ],
    leftoverStrategy: "EXPECTED",
    baseServings: 4,
    yieldText: "SERVES 4"
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "12-to-16-ounce-pork-tenderloins-trimmed-of-fat-and-silver-skin",
          displayName: "(12- to 16-ounce) pork tenderloins, trimmed of fat and silver skin",
          amount: 2,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "PROTEIN",
          shoppingCategory: "MEAT_SEAFOOD",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "table-salt",
          displayName: "table salt",
          amount: 1.25,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "ground-black-pepper",
          displayName: "ground black pepper",
          amount: 0.75,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "vegetable-oil",
          displayName: "vegetable oil",
          amount: 2,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "recipe-pan-sauce-optional-recipes-follow",
          displayName: "recipe pan sauce (optional; recipes follow)",
          amount: 1,
          unit: "UNIT",
          criticality: "NON_CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "SAUCE"
        }
  ],
  preflight: [],
  steps: [
    {
          stepNumber: 1,
          instruction: "Adjust an oven rack to middle position and heat oven to 400 degrees. Sprinkle tenderloins evenly with salt and pepper; rub seasoning into meat. Heat oil in 12-inch skillet over medium-high heat until smoking. Place both tenderloins in skillet; cook until well browned, about 3 minutes. Using tongs, rotate tenderloins quarter-turn; cook until well browned, 45 to 60 seconds. Repeat until all sides are browned, about 1 minute longer. Transfer tenderloins to rimmed baking sheet and place in oven (reserve skillet if making pan sauce); roast until internal temperature registers 140 to 145 degrees on instant-read thermometer, 10 to 16 minutes. (Begin pan sauce, if making, while meat roasts.)"
        },
    {
          stepNumber: 2,
          instruction: "Transfer tenderloins to carving board and tent loosely with foil (continue with pan sauce, if making); let rest until internal temperature registers 150 degrees, 8 to 10 minutes. Cut tenderloins crosswise into 1/2-inch-thick slices, arrange on platter or individual plates, and spoon sauce (if using) over; serve immediately."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ]
} satisfies Recipe;
