// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:22.320Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const panSearedScallops = {
  id: "atk_pan-seared-scallops",
  name: "Pan-Seared Scallops",
  slug: "pan-seared-scallops",
  metadata: {
    timeBand: "FAST",
    estimatedMinutes: 30,
    equipmentTags: [
      "LARGE_SKILLET"
    ],
    leftoverStrategy: "EXPECTED",
    baseServings: 4,
    yieldText: "SERVES 4"
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "why-this-recipes-works-for-restaurant-style-pan-seared-scallops-with-golden-brown-crusts-and-tender-interiors-we-needed-to-compensate-for-the-weaker-heating-power-of-home-stovetops-we-started-with-a-nonstick-skillet-so-that-the-browned-bits-would-form-a-crust-on-the-fish-instead-of-sticking-to-the-skillet-but-it-wasn-t-until-we-tried-a-common-restaurant-technique-butter-basting-that-our-scallops-really-improved-we-seared-the-scallops-in-oil-on-one-side-and-added-butter-to-the-skillet-after-flipping-them-we-then-spooned-the-foaming-butter-over-the-scallops-waiting-to-add-the-butter-ensured-that-it-had-just-enough-time-to-work-its-browning-magic-but-not-enough-time-to-burn-we-strongly-recommend-purchasing-dry-scallops-which-don-t-contain-chemical-additives-and-taste-better-than-wet-scallops-dry-scallops-will-look-ivory-or-pinkish-wet-scallops-are-bright-white-if-you-can-find-only-wet-scallops-soak-them-in-a-solution-of-1-quart-cold-water-1-4-cup-lemon-juice-and-2-tablespoons-table-salt-for-30-minutes-before-proceeding-with-step-1-and-season-the-scallops-with-pepper-only-in-step-2-prepare-the-sauce-if-serving-while-the-scallops-dry-between-steps-1-and-2-and-keep-it-warm-while-cooking-them",
          displayName: "WHY THIS RECIPES WORKS For restaurant-style pan-seared scallops with golden-brown crusts and tender interiors, we needed to compensate for the weaker heating power of home stovetops. We started with a nonstick skillet so that the browned bits would form a crust on the fish instead of sticking to the skillet. But it wasn’t until we tried a common restaurant technique—butter basting—that our scallops really improved. We seared the scallops in oil on one side and added butter to the skillet after flipping them. We then spooned the foaming butter over the scallops. Waiting to add the butter ensured that it had just enough time to work its browning magic, but not enough time to burn. We strongly recommend purchasing “dry” scallops, which don’t contain chemical additives and taste better than “wet” scallops. Dry scallops will look ivory or pinkish; wet scallops are bright white. If you can find only wet scallops, soak them in a solution of 1 quart cold water, 1/4 cup lemon juice, and 2 tablespoons table salt for 30 minutes before proceeding with step 1, and season the scallops with pepper only in step 2. Prepare the sauce (if serving) while the scallops dry (between steps 1 and 2) and keep it warm while cooking them.",
          amount: 1,
          unit: "UNIT",
          criticality: "NON_CRITICAL",
          kind: "OTHER",
          shoppingCategory: "OTHER",
          quantityKind: "FIXED",
          allergens: [
            "SHELLFISH",
            "DAIRY"
          ]
        },
    {
          ingredientId: "large-sea-scallops-tendons-removed",
          displayName: "large sea scallops, tendons removed",
          amount: 1.5,
          unit: "LB",
          criticality: "CRITICAL",
          kind: "PROTEIN",
          shoppingCategory: "MEAT_SEAFOOD",
          quantityKind: "FIXED",
          allergens: [
            "SHELLFISH"
          ]
        },
    {
          ingredientId: "table-salt",
          displayName: "table salt",
          amount: 0.5,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "pepper",
          displayName: "pepper",
          amount: 0.25,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "vegetable-oil-divided",
          displayName: "vegetable oil, divided",
          amount: 2,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "unsalted-butter-cut-into-2-pieces-divided",
          displayName: "unsalted butter, cut into 2 pieces, divided",
          amount: 2,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "lemon-wedges-or-lemon-browned-butter-sauce-recipe-follows",
          displayName: "Lemon wedges or Lemon Browned Butter Sauce (recipe follows)",
          amount: 1,
          unit: "UNIT",
          criticality: "NON_CRITICAL",
          kind: "FRUIT",
          shoppingCategory: "PRODUCE",
          quantityKind: "TO_TASTE",
          component: "GARNISH",
          allergens: [
            "DAIRY"
          ]
        }
  ],
  preflight: [],
  steps: [
    {
          stepNumber: 1,
          instruction: "Place scallops on rimmed baking sheet lined with clean dish towel. Place second clean dish towel on top of scallops and press gently on towel to blot liquid. Let scallops sit at room temperature for 10 minutes while towels absorb moisture."
        },
    {
          stepNumber: 2,
          instruction: "Remove second towel and sprinkle scallops on both sides with salt and pepper. Heat 1 tablespoon oil in 12-inch nonstick skillet over high heat until just smoking. Add half of scallops in single layer, flat side down, and cook, without moving, until well browned, 11/2 to 2 minutes."
        },
    {
          stepNumber: 3,
          instruction: "Add 1 tablespoon butter to skillet. Using tongs, flip scallops and continue to cook, using large spoon to baste scallops with melted butter, tilting skillet so butter runs to one side, until sides of scallops are firm and centers are opaque, 30 to 90 seconds longer (remove smaller scallops from the pan as they finish cooking)."
        },
    {
          stepNumber: 4,
          instruction: "Transfer scallops to large plate and tent with aluminum foil. Wipe out skillet with paper towels and repeat with remaining 1 tablespoon oil, remaining scallops, and remaining 1 tablespoon butter. Serve immediately with lemon wedges or sauce."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ],
  recipeAllergens: [
    "SHELLFISH",
    "DAIRY"
  ]
} satisfies Recipe;
