// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:22.406Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const paneFrancese = {
  id: "atk_pane-francese",
  name: "Pane Francese",
  slug: "pane-francese",
  metadata: {
    timeBand: "PROJECT",
    estimatedMinutes: 420,
    leftoverStrategy: "EXPECTED",
    yieldText: "MAKES 2 loaves",
    baseServings: 2,
    equipmentTags: []
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "32-3-ounces-bread-flour",
          displayName: "(32/3 ounces) bread flour",
          amount: 0.6666666666666666,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "CARB",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "SPONGE"
        },
    {
          ingredientId: "4-ounces-water-room-temperature",
          displayName: "(4 ounces) water, room temperature",
          amount: 0.5,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "SPONGE"
        },
    {
          ingredientId: "instant-or-rapid-rise-yeast",
          displayName: "instant or rapid-rise yeast",
          amount: 0.125,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "SPONGE"
        },
    {
          ingredientId: "142-3-to-61-2-ounces-bread-flour",
          displayName: "(142/3 to 61/2 ounces) bread flour",
          amount: 0.6666666666666666,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "CARB",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "DOUGH"
        },
    {
          ingredientId: "instant-or-rapid-rise-yeast",
          displayName: "instant or rapid-rise yeast",
          amount: 1.5,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "DOUGH"
        },
    {
          ingredientId: "10-ounces-water-room-temperature",
          displayName: "(10 ounces) water, room temperature",
          amount: 1.25,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "DOUGH"
        },
    {
          ingredientId: "extra-virgin-olive-oil",
          displayName: "extra-virgin olive oil",
          amount: 1,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "DOUGH"
        },
    {
          ingredientId: "table-salt",
          displayName: "table salt",
          amount: 2.25,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "DOUGH"
        }
  ],
  preflight: [
    {
          label: "Sponge",
          description: "Prepare the sponge and let it sit at room temperature until risen and beginning to collapse.",
          durationMinutes: 360,
          type: "LONG_PREP"
        },
    {
          label: "Preheat Baking Stone",
          description: "Place baking stone on upper rack with lava rocks on lower rack and preheat the oven.",
          durationMinutes: 60,
          type: "LONG_PREP"
        }
  ],
  steps: [
    {
          stepNumber: 1,
          instruction: "FOR THE SPONGE: Stir all ingredients in 4-cup liquid measuring cup with wooden spoon until well combined. Cover tightly with plastic wrap and let sit at room temperature until sponge has risen and begins to collapse, about 6 hours (sponge can sit at room temperature for up to 24 hours)."
        },
    {
          stepNumber: 2,
          instruction: "FOR THE DOUGH: Whisk 22/3 cups flour and yeast together in bowl of stand mixer. Stir water into sponge with wooden spoon until well combined. Using dough hook on low speed, slowly add sponge mixture to flour mixture and mix until cohesive dough starts to form and no dry flour remains, about 2 minutes, scraping down bowl as needed. Cover bowl tightly with plastic and let dough rest for 20 minutes."
        },
    {
          stepNumber: 3,
          instruction: "Add oil and salt to dough and knead on medium-low speed until dough is smooth and elastic and clears sides of bowl, about 10 minutes. If more flour is needed, add remaining 1/3 cup flour, 1 tablespoon at a time, until dough clears sides of bowl but sticks to bottom. Transfer dough to lightly greased large bowl or container, cover tightly with plastic, and let rise for 30 minutes."
        },
    {
          stepNumber: 4,
          instruction: "Using greased bowl scraper (or your fingertips), fold dough over itself by gently lifting and folding edge of dough toward middle. Turn bowl 45 degrees and fold dough again; repeat turning bowl and folding dough 6 more times (total of 8 folds). Cover tightly with plastic and let rise for 30 minutes. Repeat folding, then cover bowl tightly with plastic and let dough rise until nearly doubled in size, 1 to 11/2 hours."
        },
    {
          stepNumber: 5,
          instruction: "Mist underside of couche with water, drape over inverted rimmed baking sheet, and dust evenly with flour. Transfer dough to lightly floured counter. Using lightly floured hands press and stretch dough into 12 by 6-inch rectangle, deflating any gas pockets larger than 1 inch, and divide in half crosswise. Cover loosely with greased plastic."
        },
    {
          stepNumber: 6,
          instruction: "Gently press and stretch 1 piece of dough (keep remaining piece covered) into 7-inch square. Fold top corners of dough diagonally into center of square and press gently to seal. Stretch and fold upper third of dough toward center and press seam gently to seal."
        },
    {
          stepNumber: 7,
          instruction: "Stretch and fold dough in half toward you to form rough loaf with tapered ends and pinch seam closed. Roll loaf seam side down. Starting at center of loaf and working toward ends, gently and evenly roll and stretch dough until it measures 15 inches long by 21/2 inches wide. Moving your hands in opposite directions, use back and forth motion to roll ends of loaf under your palms to form sharp points."
        },
    {
          stepNumber: 8,
          instruction: "Gently slide your hands underneath each end of loaf and transfer seam side up to prepared couche. On either side of loaf, pinch couche into pleat, then cover loosely with large plastic garbage bag. Repeat steps 6 through 7 with remaining piece of dough and place on opposite side of 1 pleat. Fold edges of couche over loaves to cover completely, then carefully place sheet inside garbage bag. Tie, or fold under, open end of bag to fully enclose. Let rise until loaves increase in size by about half and dough springs back minimally when poked gently with your knuckle, 30 minutes to 1 hour (remove loaf from bag to test)."
        },
    {
          stepNumber: 9,
          instruction: "One hour before baking, adjust oven racks to lower-middle and lowest positions. Place baking stone on upper rack, place 2 disposable aluminum pie plates filled with 1 quart lava rocks each on lower rack, and heat oven to 450 degrees. Line pizza peel with 16 by 12-inch piece of parchment paper, with long edge perpendicular to handle. Bring 1 cup water to boil."
        },
    {
          stepNumber: 10,
          instruction: "Remove sheet with loaves from bag. Unfold couche, pulling from ends to remove pleats. Dust top of loaves with flour. (If any seams have reopened, pinch closed before dusting with flour.) Gently pushing with side of flipping board, roll 1 loaf over, away from other loaf, so it is seam side down. Using your hand, hold long edge of flipping board between loaf and couche at 45-degree angle, then lift couche with your other hand and flip loaf seam side up onto board. Invert loaf seam side down onto prepared pizza peel, about 2 inches from long edge of parchment, then use flipping board to straighten loaf and reshape as needed. Repeat with second loaf, leaving at least 3 inches between loaves."
        },
    {
          stepNumber: 11,
          instruction: "Carefully pour 1/2 cup boiling water into 1 disposable pie plate of preheated rocks and close oven door for 1 minute to create steam. Meanwhile, holding lame concave side up at 30-degree angle to loaf, make one 1/2-inch deep slash with swift, fluid motion lengthwise along top of loaf, starting and stopping about 1/2 inch from ends. Repeat with second loaf."
        },
    {
          stepNumber: 12,
          instruction: "Working quickly, slide parchment with loaves onto baking stone and pour remaining 1/2 cup boiling water into second disposable pie plate of preheated rocks. Bake until crust is golden brown and loaves register 205 to 210 degrees, 20 to 25 minutes, rotating loaves halfway through baking. Transfer loaves to wire rack, discard parchment, and let cool completely, about 3 hours, before serving."
        },
    {
          stepNumber: 13,
          instruction: "Gently press and stretch dough into 7-inch square. Fold top corners of dough diagonally into center of square; press gently to seal."
        },
    {
          stepNumber: 14,
          instruction: "Stretch and fold upper third of dough toward center; press seam gently to seal."
        },
    {
          stepNumber: 15,
          instruction: "Stretch and fold dough in half toward you to form rough loaf with tapered ends. Pinch seam closed, then roll loaf seam side down."
        },
    {
          stepNumber: 16,
          instruction: "Roll and stretch loaf until it measures 15 inches long by 21/2 inches wide. Moving your hands in opposite directions, use back and forth motion to roll ends of loaf under your palms to form sharp points."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ]
} satisfies Recipe;
