// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:22.459Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const parmesanFarrotto = {
  id: "atk_parmesan-farrotto",
  name: "Parmesan Farrotto",
  slug: "parmesan-farrotto",
  metadata: {
    timeBand: "NORMAL",
    estimatedMinutes: 60,
    equipmentTags: [
      "DUTCH_OVEN",
      "BLENDER"
    ],
    leftoverStrategy: "EXPECTED",
    baseServings: 6,
    yieldText: "SERVES 6"
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "whole-farro",
          displayName: "whole farro",
          amount: 1.5,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "CARB",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "chicken-broth",
          displayName: "chicken broth",
          amount: 3,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "water",
          displayName: "water",
          amount: 3,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "unsalted-butter-divided",
          displayName: "unsalted butter, divided",
          amount: 4,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "onion-chopped-fine",
          displayName: "onion, chopped fine",
          amount: 0.5,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "clove-minced",
          displayName: "clove, minced",
          amount: 1,
          unit: "GRAM",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "minced-fresh-thyme",
          displayName: "minced fresh thyme",
          amount: 2,
          unit: "TSP",
          criticality: "NON_CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "table-salt",
          displayName: "table salt",
          amount: 1,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "pepper",
          displayName: "pepper",
          amount: 0.75,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "parmesan-cheese-grated-1-cup",
          displayName: "Parmesan cheese, grated (1 cup)",
          amount: 2,
          unit: "OZ",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "minced-fresh-parsley",
          displayName: "minced fresh parsley",
          amount: 2,
          unit: "TBSP",
          criticality: "NON_CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "lemon-juice",
          displayName: "lemon juice",
          amount: 2,
          unit: "TSP",
          criticality: "NON_CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        }
  ],
  preflight: [],
  steps: [
    {
          stepNumber: 1,
          instruction: "Pulse farro in blender until about half of grains are broken into smaller pieces, about 6 pulses."
        },
    {
          stepNumber: 2,
          instruction: "Bring broth and water to boil in large saucepan over high heat. Reduce heat to medium-low to maintain gentle simmer."
        },
    {
          stepNumber: 3,
          instruction: "Melt 2 tablespoons butter in large Dutch oven over medium-low heat. Add onion and cook, stirring frequently, until softened, 3 to 4 minutes. Add garlic and stir until fragrant, about 30 seconds. Add farro and cook, stirring frequently, until grains are lightly toasted, about 3 minutes."
        },
    {
          stepNumber: 4,
          instruction: "Stir 5 cups hot broth mixture into farro mixture; reduce heat to low; cover; and cook until almost all liquid has been absorbed and farro is just al dente, about 25 minutes, stirring twice during cooking."
        },
    {
          stepNumber: 5,
          instruction: "Add thyme, salt, and pepper and continue to cook, stirring constantly, until farro becomes creamy, about 5 minutes."
        },
    {
          stepNumber: 6,
          instruction: "Off heat, stir in Parmesan, parsley, lemon juice, and remaining 2 tablespoons butter. Season with salt and pepper to taste. Adjust consistency with remaining hot broth mixture as needed. Serve immediately."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ],
  recipeAllergens: [
    "DAIRY"
  ]
} satisfies Recipe;
