// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:22.641Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const pastaWithPestoPotatoesAndGreenBeans = {
  id: "atk_pasta-with-pesto-potatoes-and-green-beans",
  name: "Pasta with Pesto, Potatoes, and Green Beans",
  slug: "pasta-with-pesto-potatoes-and-green-beans",
  metadata: {
    timeBand: "NORMAL",
    estimatedMinutes: 75,
    equipmentTags: [
      "FOOD_PROCESSOR",
      "LARGE_POT",
      "LARGE_SKILLET"
    ],
    leftoverStrategy: "EXPECTED",
    baseServings: 6,
    yieldText: "SERVES 6"
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "pine-nuts",
          displayName: "pine nuts",
          amount: 0.25,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          allergens: [
            "TREE_NUT"
          ]
        },
    {
          ingredientId: "cloves-unpeeled",
          displayName: "cloves, unpeeled",
          amount: 3,
          unit: "GRAM",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "large-red-potatoes-peeled-and-cut-into-1-2-inch-pieces",
          displayName: "large red potatoes, peeled and cut into 1/2-inch pieces",
          amount: 1,
          unit: "LB",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "table-salt-plus-salt-for-cooking-vegetables",
          displayName: "table salt, plus salt for cooking vegetables",
          amount: 0.5,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "green-beans-trimmed-and-cut-into-11-2-inch-lengths",
          displayName: "green beans, trimmed and cut into 11/2-inch lengths",
          amount: 12,
          unit: "OZ",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "fresh-basil-leaves",
          displayName: "fresh basil leaves",
          amount: 2,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          component: "PESTO"
        },
    {
          ingredientId: "parmesan-cheese-grated-1-2-cup",
          displayName: "Parmesan cheese, grated (1/2 cup)",
          amount: 1,
          unit: "OZ",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          component: "PESTO",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "extra-virgin-olive-oil",
          displayName: "extra-virgin olive oil",
          amount: 7,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "PESTO"
        },
    {
          ingredientId: "gemelli",
          displayName: "gemelli",
          amount: 1,
          unit: "LB",
          criticality: "CRITICAL",
          kind: "CARB",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "unsalted-butter-cut-into-1-2-inch-pieces-and-chilled",
          displayName: "unsalted butter, cut into 1/2-inch pieces and chilled",
          amount: 2,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "lemon-juice",
          displayName: "lemon juice",
          amount: 1,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "pepper",
          displayName: "pepper",
          amount: 0.5,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        }
  ],
  preflight: [],
  steps: [
    {
          stepNumber: 1,
          instruction: "Toast pine nuts and garlic in 10-inch skillet over medium heat, stirring frequently, until pine nuts are golden and fragrant and garlic darkens slightly, 3 to 5 minutes. Transfer to bowl and let cool. Peel garlic and chop coarse."
        },
    {
          stepNumber: 2,
          instruction: "Bring 3 quarts water to boil in large pot. Add potatoes and 1 tablespoon salt and cook until potatoes are tender but still hold their shape, 9 to 12 minutes. Using slotted spoon, transfer potatoes to rimmed baking sheet. (Do not discard water.)"
        },
    {
          stepNumber: 3,
          instruction: "Meanwhile, bring 1/2 cup water and 1/4 teaspoon salt to boil in now-empty skillet over medium heat. Add green beans, cover, and cook until tender, 5 to 8 minutes. Drain green beans and transfer to sheet with potatoes."
        },
    {
          stepNumber: 4,
          instruction: "Process basil, Parmesan, oil, pine nuts, garlic, and salt in food processor until smooth, about 1 minute."
        },
    {
          stepNumber: 5,
          instruction: "Add pasta to water in large pot and cook, stirring often, until al dente. Set colander in large bowl. Drain pasta in colander, reserving cooking water in bowl. Return pasta to pot. Add butter, lemon juice, pepper, potatoes and green beans, pesto, and 11/4 cups reserved cooking water and stir vigorously with rubber spatula until sauce takes on creamy appearance. Add additional cooking water as needed to adjust consistency and season with salt and pepper to taste. Serve immediately."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ],
  recipeAllergens: [
    "TREE_NUT",
    "DAIRY"
  ]
} satisfies Recipe;
