// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:22.593Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const pastaWithBurstCherryTomatoSauceAndFriedCaperCrumbs = {
  id: "atk_pasta-with-burst-cherry-tomato-sauce-and-fried-caper-crumbs",
  name: "Pasta with Burst Cherry Tomato Sauce and Fried Caper Crumbs",
  slug: "pasta-with-burst-cherry-tomato-sauce-and-fried-caper-crumbs",
  metadata: {
    timeBand: "NORMAL",
    estimatedMinutes: 60,
    equipmentTags: [
      "LARGE_POT"
    ],
    leftoverStrategy: "EXPECTED",
    baseServings: 4,
    yieldText: "SERVES 4 to 6"
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "extra-virgin-olive-oil",
          displayName: "extra-virgin olive oil",
          amount: 2,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "TOPPING"
        },
    {
          ingredientId: "capers-rinsed-and-patted-dry",
          displayName: "capers, rinsed and patted dry",
          amount: 0.25,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "TOPPING"
        },
    {
          ingredientId: "anchovy-fillet-rinsed-patted-dry-and-minced",
          displayName: "anchovy fillet, rinsed, patted dry, and minced",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "PROTEIN",
          shoppingCategory: "MEAT_SEAFOOD",
          quantityKind: "FIXED",
          component: "TOPPING",
          allergens: [
            "FISH"
          ]
        },
    {
          ingredientId: "panko-bread-crumbs",
          displayName: "panko bread crumbs",
          amount: 0.5,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "CARB",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "TOPPING"
        },
    {
          ingredientId: "table-salt",
          displayName: "table salt",
          amount: 0.125,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "TOPPING"
        },
    {
          ingredientId: "pepper",
          displayName: "pepper",
          amount: 0.125,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "TOPPING"
        },
    {
          ingredientId: "minced-fresh-parsley",
          displayName: "minced fresh parsley",
          amount: 0.25,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          component: "TOPPING"
        },
    {
          ingredientId: "grated-lemon-zest",
          displayName: "grated lemon zest",
          amount: 1,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          component: "TOPPING"
        },
    {
          ingredientId: "extra-virgin-olive-oil",
          displayName: "extra-virgin olive oil",
          amount: 0.25,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "SAUCE"
        },
    {
          ingredientId: "cloves-sliced-thin",
          displayName: "cloves, sliced thin",
          amount: 2,
          unit: "GRAM",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          component: "SAUCE"
        },
    {
          ingredientId: "anchovy-fillets-rinsed-and-patted-dry",
          displayName: "anchovy fillets, rinsed and patted dry",
          amount: 2,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "PROTEIN",
          shoppingCategory: "MEAT_SEAFOOD",
          quantityKind: "FIXED",
          component: "SAUCE",
          allergens: [
            "FISH"
          ]
        },
    {
          ingredientId: "cherry-tomatoes",
          displayName: "cherry tomatoes",
          amount: 2,
          unit: "LB",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          component: "SAUCE"
        },
    {
          ingredientId: "table-salt-plus-salt-for-cooking-pasta",
          displayName: "table salt, plus salt for cooking pasta",
          amount: 1.5,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "SAUCE"
        },
    {
          ingredientId: "sugar",
          displayName: "sugar",
          amount: 0.25,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "CARB",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "SAUCE"
        },
    {
          ingredientId: "1-8-1-4-teaspoon-red-pepper-flakes",
          displayName: "1/8–1/4 teaspoon red pepper flakes",
          amount: 1,
          unit: "UNIT",
          criticality: "NON_CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "APPROXIMATE",
          component: "SAUCE"
        },
    {
          ingredientId: "penne-rigate-orecchiette-campanelle-or-other-short-pasta",
          displayName: "penne rigate, orecchiette, campanelle, or other short pasta",
          amount: 12,
          unit: "OZ",
          criticality: "CRITICAL",
          kind: "CARB",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "unsalted-butter-cut-into-2-pieces-and-chilled",
          displayName: "unsalted butter, cut into 2 pieces and chilled",
          amount: 2,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "fresh-basil-leaves-torn-if-large",
          displayName: "fresh basil leaves, torn if large",
          amount: 1,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          component: "GARNISH"
        }
  ],
  preflight: [],
  steps: [
    {
          stepNumber: 1,
          instruction: "FOR THE TOPPING: Heat oil in 10-inch skillet over medium heat until shimmering. Add capers and anchovy and cook, stirring frequently, until capers have darkened and shrunk, 3 to 4 minutes. Using slotted spoon, transfer caper mixture to paper towel–lined plate; set aside. Leave oil in skillet and return skillet to medium heat. Add panko, salt, and pepper to skillet and cook, stirring constantly, until panko is golden brown, 4 to 5 minutes. Transfer panko to medium bowl. Stir in parsley, lemon zest, and reserved caper mixture."
        },
    {
          stepNumber: 2,
          instruction: "FOR THE PASTA: Bring 4 quarts water to boil in large pot. While water is coming to boil, heat oil, garlic, and anchovies in large saucepan over medium heat. Cook, stirring occasionally, until anchovies break down and garlic is lightly browned, 4 to 5 minutes. Add tomatoes, salt, sugar, and pepper flakes to saucepan and stir to combine. Cover and increase heat to medium-high. Cook, without stirring, for 10 minutes."
        },
    {
          stepNumber: 3,
          instruction: "Meanwhile, add pasta and 1 tablespoon salt to boiling water. Cook, stirring often, until al dente. Reserve 1/2 cup cooking water, then drain pasta and return it to pot. Off heat, add butter and tomato mixture to pasta and stir gently until oil, butter, and tomato juices combine to form light sauce, about 15 seconds. Adjust consistency with reserved cooking water as needed, adding 2 tablespoons at a time. Stir in basil and season with salt to taste. Serve, passing topping separately."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ],
  recipeAllergens: [
    "FISH",
    "DAIRY"
  ]
} satisfies Recipe;
