// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:22.519Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const pastaAndFreshTomatoSauceWithGarlicAndBasil = {
  id: "atk_pasta-and-fresh-tomato-sauce-with-garlic-and-basil",
  name: "Pasta and Fresh Tomato Sauce with Garlic and Basil",
  slug: "pasta-and-fresh-tomato-sauce-with-garlic-and-basil",
  metadata: {
    timeBand: "NORMAL",
    estimatedMinutes: 45,
    equipmentTags: [
      "LARGE_SKILLET",
      "LARGE_POT"
    ],
    leftoverStrategy: "EXPECTED",
    baseServings: 5,
    yieldText: "SERVES 4 to 6"
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "extra-virgin-olive-oil",
          displayName: "extra-virgin olive oil",
          amount: 3,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "medium-garlic-cloves-minced-or-pressed-through-a-garlic-press-about-2-teaspoons",
          displayName: "medium garlic cloves, minced or pressed through a garlic press (about 2 teaspoons)",
          amount: 2,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "APPROXIMATE"
        },
    {
          ingredientId: "ripe-tomatoes-about-4-large-cored-peeled-seeded-and-cut-into-1-2-inch-pieces",
          displayName: "ripe tomatoes (about 4 large), cored, peeled, seeded, and cut into 1/2-inch pieces",
          amount: 2,
          unit: "LB",
          criticality: "CRITICAL",
          kind: "FRUIT",
          shoppingCategory: "PRODUCE",
          quantityKind: "APPROXIMATE"
        },
    {
          ingredientId: "chopped-fresh-basil-leaves",
          displayName: "chopped fresh basil leaves",
          amount: 2,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PRODUCE",
          quantityKind: "APPROXIMATE"
        },
    {
          ingredientId: "table-salt",
          displayName: "Table salt",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "TO_TASTE"
        },
    {
          ingredientId: "penne-fusilli-or-other-short-tubular-pasta-see-note",
          displayName: "penne, fusilli, or other short tubular pasta (see note)",
          amount: 1,
          unit: "LB",
          criticality: "CRITICAL",
          kind: "CARB",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        }
  ],
  preflight: [],
  steps: [
    {
          stepNumber: 1,
          instruction: "Cook 2 tablespoons of the oil and the garlic in a 10-inch skillet over medium heat until fragrant, about 30 seconds. Stir in the tomatoes and cook over medium-high heat until the liquid released by the tomatoes evaporates and the tomato pieces form a chunky sauce, about 10 minutes. Stir in the basil and salt to taste; cover."
        },
    {
          stepNumber: 2,
          instruction: "Meanwhile, bring 4 quarts water to a boil in a large pot. Add 1 tablespoon salt and the pasta to the boiling water and cook, stirring often, until al dente. Reserve 1/2 cup of the cooking water then drain the pasta and return it to the pot. Add 1/4 cup of the reserved cooking water, the sauce, and the remaining 1 tablespoon oil and toss to combine. Adjust the consistency of the sauce with the remaining reserved pasta cooking water as needed. Serve."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food",
    "weeknight"
  ]
} satisfies Recipe;
