// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:23.117Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const pressureCookerChickenNoodleSoup = {
  id: "atk_pressure-cooker-chicken-noodle-soup",
  name: "Pressure-Cooker Chicken Noodle Soup",
  slug: "pressure-cooker-chicken-noodle-soup",
  metadata: {
    timeBand: "NORMAL",
    estimatedMinutes: 75,
    leftoverStrategy: "EXPECTED",
    baseServings: 8,
    yieldText: "SERVES 8",
    equipmentTags: []
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "vegetable-oil",
          displayName: "vegetable oil",
          amount: 1,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "onion-chopped-fine",
          displayName: "onion, chopped fine",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "cloves-minced-about-1-teaspoon",
          displayName: "cloves, minced (about 1 teaspoon)",
          amount: 3,
          unit: "GRAM",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "minced-fresh-thyme-or-1-4-teaspoon-dried",
          displayName: "minced fresh thyme or 1/4 teaspoon dried",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "APPROXIMATE"
        },
    {
          ingredientId: "water",
          displayName: "water",
          amount: 8,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "carrots-peeled-and-sliced",
          displayName: "carrots, peeled and sliced",
          amount: 4,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "celery-ribs-sliced-1-2-inch-thick",
          displayName: "celery ribs, sliced 1/2 inch thick",
          amount: 2,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "soy-sauce",
          displayName: "soy sauce",
          amount: 2,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          allergens: [
            "SOY"
          ]
        },
    {
          ingredientId: "whole-chicken-giblets-discarded",
          displayName: "whole chicken, giblets discarded",
          amount: 1,
          unit: "LB",
          criticality: "CRITICAL",
          kind: "PROTEIN",
          shoppingCategory: "MEAT_SEAFOOD",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "table-salt-and-pepper",
          displayName: "Table salt and pepper",
          amount: 1,
          unit: "UNIT",
          criticality: "NON_CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "TO_TASTE"
        },
    {
          ingredientId: "22-3-cups-wide-egg-noodles",
          displayName: "(22/3 cups) wide egg noodles",
          amount: 4,
          unit: "OZ",
          criticality: "CRITICAL",
          kind: "CARB",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          allergens: [
            "EGG"
          ]
        },
    {
          ingredientId: "minced-fresh-parsley",
          displayName: "minced fresh parsley",
          amount: 0.25,
          unit: "CUP",
          criticality: "NON_CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        }
  ],
  preflight: [],
  steps: [
    {
          stepNumber: 1,
          instruction: "Heat oil in pressure-cooker pot over medium heat until shimmering. Add onion and cook until softened, about 5 minutes. Stir in garlic and thyme and cook until fragrant, about 30 seconds. Stir in water, carrots, celery, and soy sauce, scraping up any browned bits. Season chicken with salt and pepper and place, breast side up, in pot."
        },
    {
          stepNumber: 2,
          instruction: "Lock pressure-cooker lid in place and bring to high pressure over medium-high heat. As soon as pot reaches high pressure, reduce heat to medium-low and cook for 20 minutes, adjusting heat as needed to maintain high pressure."
        },
    {
          stepNumber: 3,
          instruction: "Remove pot from heat. Quick release pressure, then carefully remove lid, allowing steam to escape away from you."
        },
    {
          stepNumber: 4,
          instruction: "Transfer chicken to cutting board, let cool slightly, then shred meat into bite-size pieces, discarding skin and bones. Meanwhile, using large spoon, skim excess fat from surface of soup. Bring soup to boil, stir in noodles, and cook until tender, about 5 minutes. Stir in shredded chicken and parsley, season with salt and pepper to taste, and serve."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ],
  recipeAllergens: [
    "SOY",
    "EGG"
  ]
} satisfies Recipe;
