// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:23.145Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const pupusas = {
  id: "atk_pupusas",
  name: "Pupusas",
  slug: "pupusas",
  metadata: {
    timeBand: "NORMAL",
    estimatedMinutes: 75,
    equipmentTags: [
      "FOOD_PROCESSOR"
    ],
    leftoverStrategy: "EXPECTED",
    yieldText: "MAKES 8 pupusas",
    baseServings: 8
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "8-ounces-masa-harina",
          displayName: "(8 ounces) masa harina",
          amount: 2,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "CARB",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "table-salt",
          displayName: "table salt",
          amount: 0.5,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "boiling-water-plus-warm-tap-water-as-needed",
          displayName: "boiling water, plus warm tap water as needed",
          amount: 2,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "vegetable-oil-divided",
          displayName: "vegetable oil, divided",
          amount: 2,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "cotija-cheese-cut-into-2-pieces",
          displayName: "cotija cheese, cut into 2 pieces",
          amount: 2,
          unit: "OZ",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          component: "FILLING",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "monterey-jack-cheese-cut-into-8-pieces",
          displayName: "Monterey Jack cheese, cut into 8 pieces",
          amount: 8,
          unit: "OZ",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          component: "FILLING",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "recipe-quick-salsa-this-page",
          displayName: "recipe Quick Salsa (this page)",
          amount: 1,
          unit: "UNIT",
          criticality: "NON_CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "ACCOMPANIMENT"
        },
    {
          ingredientId: "recipe-curtido-this-page",
          displayName: "recipe Curtido (this page)",
          amount: 1,
          unit: "UNIT",
          criticality: "NON_CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          component: "ACCOMPANIMENT"
        }
  ],
  preflight: [
    {
          durationMinutes: 20,
          description: "Let masa harina dough rest",
          optional: false,
          type: "LONG_PREP"
        }
  ],
  steps: [
    {
          stepNumber: 1,
          instruction: "Using marker, draw 4-inch circle in center of 1 side of 1-quart or 1-gallon zipper-lock bag. Cut open seams along both sides of bag, but leave bottom seam intact so bag opens completely."
        },
    {
          stepNumber: 2,
          instruction: "Mix masa harina and salt together in medium bowl. Add boiling water and 1 teaspoon oil and mix with rubber spatula until soft dough forms. Cover dough and let rest for 20 minutes."
        },
    {
          stepNumber: 3,
          instruction: "While dough rests, line rimmed baking sheet with parchment paper. Process cotija in food processor until cotija is finely chopped and resembles wet sand, about 20 seconds. Add Monterey Jack and process until mixture resembles wet oatmeal, about 30 seconds (it will not form cohesive mass). Remove processor blade. Form cheese mixture into 8 balls, weighing about 11/4 ounces each, and place balls on 1 half of prepared sheet."
        },
    {
          stepNumber: 4,
          instruction: "Knead dough in bowl for 15 to 20 seconds. Test dough’s hydration by flattening golf ball–size piece. If cracks larger than 1/4 inch form around edges, add warm tap water, 2 teaspoons at a time, until dough is soft and slightly tacky. Transfer dough to counter, shape into large ball, and divide into 8 equal pieces. Using your damp hands, roll 1 dough piece into ball and place on empty half of prepared sheet. Cover with damp dish towel. Repeat with remaining dough pieces."
        },
    {
          stepNumber: 5,
          instruction: "Place open cut bag marked side down on counter. Place 1 dough ball in center of circle. Fold other side of bag over ball. Using glass pie plate or 8-inch square baking dish, gently press dough to 4-inch diameter, using circle drawn on bag as guide. Turn out disk into your palm and place 1 cheese ball in center. Bring sides of dough up around filling and pinch top to seal. Remoisten your hands and roll ball until smooth, smoothing any cracks with your damp fingertip. Return ball to bag and slowly press to 4-inch diameter. Pinch closed any small cracks that form at edges. Return pupusa to sheet and cover with damp dish towel. Repeat with remaining dough and filling."
        },
    {
          stepNumber: 6,
          instruction: "Heat remaining 1 teaspoon oil in 12-inch nonstick skillet over medium-high heat until shimmering. Wipe skillet clean with paper towels. Carefully lay 4 pupusas in skillet and cook until spotty brown on both sides, 2 to 4 minutes per side. Transfer to platter and repeat with remaining 4 pupusas. Serve warm with salsa and curtido."
        },
    {
          stepNumber: 7,
          instruction: "Using marker, draw 4-inch circle in center of 1 side of 1-quart or 1-gallon zipper-lock bag. Cut open seams along both sides of bag, but leave bottom seam intact so bag opens completely."
        },
    {
          stepNumber: 8,
          instruction: "Place open cut bag marked side down on counter. Place dough ball in center of circle. Fold other side of bag over ball. Using glass pie plate, gently press dough to 4-inch diameter."
        },
    {
          stepNumber: 9,
          instruction: "Turn out disk into your palm and place cheese ball in center. Bring sides of dough up around filling; pinch to seal. Remoisten your hands and roll ball, smoothing any cracks with your damp fingertip."
        },
    {
          stepNumber: 10,
          instruction: "Return ball to zipper-lock bag and use pie plate to slowly press to 4-inch diameter. Pinch closed any small cracks that form at edges. Repeat steps 2 through 4 with remaining dough and filling."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ],
  recipeAllergens: [
    "DAIRY"
  ]
} satisfies Recipe;
