// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:23.228Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const quickRoastedAcornSquashWithBrownSugar = {
  id: "atk_quick-roasted-acorn-squash-with-brown-sugar",
  name: "Quick Roasted Acorn Squash with Brown Sugar",
  slug: "quick-roasted-acorn-squash-with-brown-sugar",
  metadata: {
    timeBand: "NORMAL",
    estimatedMinutes: 50,
    equipmentTags: [
      "OVEN"
    ],
    leftoverStrategy: "EXPECTED",
    baseServings: 4,
    yieldText: "SERVES 4"
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "acorn-squash-about-11-2-pounds-each-halved-pole-to-pole-and-seeded",
          displayName: "acorn squash (about 11/2 pounds each), halved pole to pole and seeded",
          amount: 2,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "table-salt",
          displayName: "Table salt",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "TO_TASTE"
        },
    {
          ingredientId: "unsalted-butter",
          displayName: "unsalted butter",
          amount: 3,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "dark-brown-sugar",
          displayName: "dark brown sugar",
          amount: 3,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        }
  ],
  preflight: [],
  steps: [
    {
          stepNumber: 1,
          instruction: "Sprinkle the squash halves with salt and place the halves, cut side down, in a 13 by 9-inch microwave-safe baking dish or arrange the halves in a large (4-quart) microwave-safe bowl so that the cut sides face out. (If using Pyrex, add 1/4 cup water to the dish or bowl.) Cover tightly with plastic wrap, using multiple sheets, if necessary; with a paring knife, poke four steam vents in the wrap. Microwave on high power until the squash is very tender and offers no resistance when pierced with a paring knife, 15 to 25 minutes. Using potholders, remove the baking dish or bowl from the microwave and set on a clean, dry surface (avoid damp or cold surfaces)."
        },
    {
          stepNumber: 2,
          instruction: "While the squash is cooking, adjust an oven rack to the highest position (about 6 inches from the broiler element) and heat the broiler. Melt the butter, brown sugar, and 1/8 teaspoon salt in a small saucepan over low heat, whisking occasionally, until combined."
        },
    {
          stepNumber: 3,
          instruction: "When the squash is cooked, carefully pull back the plastic wrap from the side farthest from you. Using tongs, transfer the cooked squash halves, cut side up, to a rimmed baking sheet. Spoon a portion of the butter-sugar mixture onto each squash half. Broil until brown and caramelized, 5 to 8 minutes, rotating the baking sheet halfway through the cooking time and removing the squash halves as they are done. Serve immediately."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ],
  recipeAllergens: [
    "DAIRY"
  ]
} satisfies Recipe;
