// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:23.331Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const redChileChickenFilling = {
  id: "atk_red-chile-chicken-filling",
  name: "Red Chile Chicken Filling",
  slug: "red-chile-chicken-filling",
  metadata: {
    timeBand: "NORMAL",
    estimatedMinutes: 90,
    equipmentTags: [
      "BLENDER",
      "LARGE_SKILLET"
    ],
    leftoverStrategy: "EXPECTED",
    yieldText: "MAKES enough for 18 tamales",
    baseServings: 18
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "dried-ancho-chiles-stemmed-seeded-and-torn-into-1-2-inch-pieces-1-cup",
          displayName: "dried ancho chiles, stemmed, seeded, and torn into 1/2-inch pieces (1 cup)",
          amount: 4,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "dried-new-mexican-chiles-stemmed-seeded-and-torn-into-1-2-inch-pieces-1-cup",
          displayName: "dried New Mexican chiles, stemmed, seeded, and torn into 1/2-inch pieces (1 cup)",
          amount: 4,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "vegetable-oil",
          displayName: "vegetable oil",
          amount: 3,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "large-onion-chopped",
          displayName: "large onion, chopped",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "cloves-minced",
          displayName: "cloves, minced",
          amount: 6,
          unit: "GRAM",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "ground-cumin",
          displayName: "ground cumin",
          amount: 0.75,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "dried-oregano",
          displayName: "dried oregano",
          amount: 0.75,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "table-salt-divided",
          displayName: "table salt, divided",
          amount: 1,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "chicken-broth",
          displayName: "chicken broth",
          amount: 3,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "pepper",
          displayName: "pepper",
          amount: 0.5,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "boneless-skinless-chicken-thighs-trimmed",
          displayName: "boneless, skinless chicken thighs, trimmed",
          amount: 1.25,
          unit: "LB",
          criticality: "CRITICAL",
          kind: "PROTEIN",
          shoppingCategory: "MEAT_SEAFOOD",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "cider-vinegar",
          displayName: "cider vinegar",
          amount: 1.5,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "sugar",
          displayName: "Sugar",
          amount: 1,
          unit: "UNIT",
          criticality: "NON_CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        }
  ],
  preflight: [],
  steps: [
    {
          stepNumber: 1,
          instruction: "Toast anchos and New Mexican chiles in 12-inch skillet over medium heat, stirring frequently, until fragrant, 2 to 6 minutes; transfer to bowl."
        },
    {
          stepNumber: 2,
          instruction: "Heat oil in now-empty skillet over medium heat until shimmering. Add onion and cook until softened, 5 to 7 minutes. Stir in garlic, cumin, oregano, 1/2 teaspoon salt, and toasted chiles and cook for 30 seconds. Stir in broth and simmer until slightly reduced, about 10 minutes. Transfer mixture to blender and process until smooth, about 20 seconds; return to skillet."
        },
    {
          stepNumber: 3,
          instruction: "Sprinkle chicken with pepper and remaining 1/2 teaspoon salt, nestle into skillet, and bring to simmer over medium heat. Cover; reduce heat to low; and cook until chicken registers 160 degrees, 20 to 25 minutes."
        },
    {
          stepNumber: 4,
          instruction: "Transfer chicken to carving board and let cool slightly. Using 2 forks, shred chicken into small pieces. Stir vinegar into sauce and season with salt, pepper, and sugar to taste. Toss shredded chicken with 1 cup sauce. Reserve remaining sauce to serve with tamales."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ]
} satisfies Recipe;
