// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:23.347Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const redLentilSoupWithWarmSpices = {
  id: "atk_red-lentil-soup-with-warm-spices",
  name: "Red Lentil Soup with Warm Spices",
  slug: "red-lentil-soup-with-warm-spices",
  metadata: {
    timeBand: "NORMAL",
    estimatedMinutes: 60,
    equipmentTags: [
      "LARGE_SKILLET"
    ],
    leftoverStrategy: "EXPECTED",
    baseServings: 4,
    yieldText: "SERVES 4 to 6"
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "unsalted-butter-divided",
          displayName: "unsalted butter, divided",
          amount: 4,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "large-onion-chopped-fine",
          displayName: "large onion, chopped fine",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "table-salt",
          displayName: "table salt",
          amount: 1,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "TO_TASTE"
        },
    {
          ingredientId: "ground-coriander",
          displayName: "ground coriander",
          amount: 0.75,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "ground-cumin",
          displayName: "ground cumin",
          amount: 0.5,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "ground-ginger",
          displayName: "ground ginger",
          amount: 0.25,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "pepper",
          displayName: "pepper",
          amount: 0.25,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "ground-cinnamon",
          displayName: "ground cinnamon",
          amount: 0.125,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "pinch-cayenne-pepper",
          displayName: "Pinch cayenne pepper",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "tomato-paste",
          displayName: "tomato paste",
          amount: 1,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "clove-minced",
          displayName: "clove, minced",
          amount: 1,
          unit: "GRAM",
          criticality: "NON_CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "chicken-broth",
          displayName: "chicken broth",
          amount: 4,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "water",
          displayName: "water",
          amount: 2,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "11-2-cups-red-lentils-picked-over-and-rinsed",
          displayName: "(11/2 cups) red lentils, picked over and rinsed",
          amount: 50.5,
          unit: "OZ",
          criticality: "CRITICAL",
          kind: "CARB",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "lemon-juice-plus-extra-for-seasoning",
          displayName: "lemon juice, plus extra for seasoning",
          amount: 2,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "TO_TASTE"
        },
    {
          ingredientId: "dried-mint-crumbled",
          displayName: "dried mint, crumbled",
          amount: 1.5,
          unit: "TSP",
          criticality: "NON_CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "Spiced Butter"
        },
    {
          ingredientId: "paprika",
          displayName: "paprika",
          amount: 1,
          unit: "TSP",
          criticality: "NON_CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "Spiced Butter"
        },
    {
          ingredientId: "chopped-fresh-cilantro",
          displayName: "chopped fresh cilantro",
          amount: 0.25,
          unit: "CUP",
          criticality: "NON_CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          component: "Garnish"
        }
  ],
  preflight: [],
  steps: [
    {
          stepNumber: 1,
          instruction: "Melt 2 tablespoons butter in large saucepan over medium heat. Add onion and salt and cook, stirring occasionally, until softened but not browned, about 5 minutes. Add coriander, cumin, ginger, pepper, cinnamon, and cayenne and cook until fragrant, about 2 minutes. Stir in tomato paste and garlic and cook for 1 minute. Stir in broth, water, and lentils and bring to simmer. Simmer vigorously, stirring occasionally, until lentils are soft and about half are broken down, about 15 minutes."
        },
    {
          stepNumber: 2,
          instruction: "Whisk soup vigorously until it is coarsely pureed, about 30 seconds. Stir in lemon juice and season with salt and extra lemon juice to taste. Cover and keep warm. (Soup can be refrigerated for up to 3 days. Thin soup with water, if desired, when reheating.)"
        },
    {
          stepNumber: 3,
          instruction: "Melt remaining 2 tablespoons butter in small skillet over medium-low heat. Remove from heat and stir in mint and paprika. Ladle soup into individual bowls, drizzle each portion with 1 teaspoon spiced butter, sprinkle with cilantro, and serve."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ],
  recipeAllergens: [
    "DAIRY"
  ]
} satisfies Recipe;
