// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:23.625Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const roastedGarlicSalsaVerde = {
  id: "atk_roasted-garlic-salsa-verde",
  name: "Roasted Garlic Salsa Verde",
  slug: "roasted-garlic-salsa-verde",
  metadata: {
    timeBand: "FAST",
    estimatedMinutes: 20,
    equipmentTags: [
      "OVEN",
      "FOOD_PROCESSOR"
    ],
    leftoverStrategy: "EXPECTED",
    yieldText: "MAKES 1/2 cup",
    baseServings: 4
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "head-cloves-separated-unpeeled",
          displayName: "head, cloves separated, unpeeled",
          amount: 1,
          unit: "GRAM",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "extra-virgin-olive-oil-divided",
          displayName: "extra-virgin olive oil, divided",
          amount: 5,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "lemon-juice",
          displayName: "lemon juice",
          amount: 2,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "fresh-parsley-leaves",
          displayName: "fresh parsley leaves",
          amount: 1,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "anchovy-fillets-rinsed-and-patted-dry",
          displayName: "anchovy fillets, rinsed and patted dry",
          amount: 2,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "PROTEIN",
          shoppingCategory: "MEAT_SEAFOOD",
          quantityKind: "FIXED",
          allergens: [
            "FISH"
          ]
        },
    {
          ingredientId: "capers-rinsed",
          displayName: "capers, rinsed",
          amount: 2,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "table-salt",
          displayName: "table salt",
          amount: 0.25,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "TO_TASTE"
        },
    {
          ingredientId: "red-pepper-flakes",
          displayName: "red pepper flakes",
          amount: 0.25,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "TO_TASTE"
        }
  ],
  preflight: [],
  steps: [
    {
          stepNumber: 1,
          instruction: "While oven preheats for Oven-Roasted Chicken Thighs, toss garlic cloves and 1 tablespoon oil in bowl. Cover bowl and microwave until garlic is softened, 2 to 5 minutes, stirring once halfway through. Place garlic in center of 12-inch square of aluminum foil. Cover with second 12-inch square of foil; fold edges together to create packet about 7 inches square. Place packet on middle rack of oven for 10 minutes."
        },
    {
          stepNumber: 2,
          instruction: "Remove packet from oven and squeeze garlic cloves out of skins. Process garlic, lemon juice, parsley, anchovies, capers, and salt in food processor until coarsely chopped, about 5 seconds. Add remaining 1/4 cup oil and pepper flakes; pulse until combined, scraping bowl as necessary."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ],
  recipeAllergens: [
    "FISH"
  ]
} satisfies Recipe;
