// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:23.458Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const roastButterfliedLegOfLambWithCorianderCuminAndMustardSeeds = {
  id: "atk_roast-butterflied-leg-of-lamb-with-coriander-cumin-and-mustard-seeds",
  name: "Roast Butterflied Leg of Lamb with Coriander, Cumin, and Mustard Seeds",
  slug: "roast-butterflied-leg-of-lamb-with-coriander-cumin-and-mustard-seeds",
  metadata: {
    timeBand: "NORMAL",
    estimatedMinutes: 180,
    equipmentTags: [
      "OVEN",
      "SHEET_PAN"
    ],
    leftoverStrategy: "EXPECTED",
    baseServings: 8,
    yieldText: "SERVES 8 to 10"
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "6-to-8-pound-butterflied-leg-of-lamb",
          displayName: "(6- to 8-pound) butterflied leg of lamb",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "PROTEIN",
          shoppingCategory: "MEAT_SEAFOOD",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "kosher-salt",
          displayName: "kosher salt",
          amount: 2,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "vegetable-oil",
          displayName: "vegetable oil",
          amount: 0.3333333333333333,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "shallots-sliced-thin",
          displayName: "shallots, sliced thin",
          amount: 3,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "cloves-peeled-and-smashed",
          displayName: "cloves, peeled and smashed",
          amount: 4,
          unit: "GRAM",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "1-inch-piece-ginger-sliced-into-1-2-inch-thick-rounds-and-smashed",
          displayName: "(1-inch) piece ginger, sliced into 1/2-inch-thick rounds and smashed",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "coriander-seeds",
          displayName: "coriander seeds",
          amount: 1,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "cumin-seeds",
          displayName: "cumin seeds",
          amount: 1,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "mustard-seeds",
          displayName: "mustard seeds",
          amount: 1,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "bay-leaves",
          displayName: "bay leaves",
          amount: 3,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "2-inch-strips-lemon-zest",
          displayName: "(2-inch) strips lemon zest",
          amount: 2,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "chopped-fresh-mint",
          displayName: "chopped fresh mint",
          amount: 0.3333333333333333,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          component: "SAUCE"
        },
    {
          ingredientId: "chopped-fresh-cilantro",
          displayName: "chopped fresh cilantro",
          amount: 0.3333333333333333,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          component: "SAUCE"
        },
    {
          ingredientId: "shallot-minced",
          displayName: "shallot, minced",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          component: "SAUCE"
        },
    {
          ingredientId: "lemon-juice",
          displayName: "lemon juice",
          amount: 2,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          component: "SAUCE"
        }
  ],
  preflight: [],
  steps: [
    {
          stepNumber: 1,
          instruction: "FOR THE LAMB: Place lamb on cutting board with fat cap facing down. Using sharp knife, trim any pockets of fat and connective tissue from underside of lamb. Flip lamb over, trim fat cap so it’s between 1/8 and 1/4 inch thick, and pound roast to even 1-inch thickness. Cut slits, spaced 1/2 inch apart, in fat cap in crosshatch pattern, being careful to cut down to but not into meat. Rub salt over entire roast and into slits. Let stand, uncovered, at room temperature for 1 hour."
        },
    {
          stepNumber: 2,
          instruction: "Meanwhile, adjust oven racks 4 to 5 inches from broiler element and to lower-middle position and heat oven to 250 degrees. Stir together oil, shallots, garlic, ginger, coriander seeds, cumin seeds, mustard seeds, bay leaves, and lemon zest on rimmed baking sheet and bake on lower rack until spices are softened and fragrant and shallots and garlic turn golden, about 1 hour. Remove sheet from oven and discard bay leaves."
        },
    {
          stepNumber: 3,
          instruction: "Thoroughly pat lamb dry with paper towels and transfer, fat side up, to sheet (directly on top of spices). Roast on lower rack until lamb registers 120 degrees, 30 to 40 minutes. Remove sheet from oven and heat broiler. Broil lamb on upper rack until surface is well browned and charred in spots and lamb registers 125 degrees, 3 to 8 minutes for medium-rare."
        },
    {
          stepNumber: 4,
          instruction: "Remove sheet from oven and, using 2 pairs of tongs, transfer lamb to carving board (some spices will cling to bottom of roast); tent with aluminum foil and let rest for 20 minutes."
        },
    {
          stepNumber: 5,
          instruction: "FOR THE SAUCE: Meanwhile, carefully pour pan juices through fine-mesh strainer into medium bowl, pressing on solids to extract as much liquid as possible; discard solids. Stir in mint, cilantro, shallot, and lemon juice. Add any accumulated lamb juices to sauce and season with salt and pepper to taste."
        },
    {
          stepNumber: 6,
          instruction: "With long side facing you, slice lamb with grain into 3 equal pieces. Turn each piece and slice across grain into 1/4-inch-thick slices. Serve with sauce. (Briefly warm sauce in microwave if it has cooled and thickened.)"
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ],
  recipeAllergens: [
    "DAIRY"
  ]
} satisfies Recipe;
