// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:23.492Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const roastRackOfLambWithRoastedRedPepperRelish = {
  id: "atk_roast-rack-of-lamb-with-roasted-red-pepper-relish",
  name: "Roast Rack of Lamb with Roasted Red Pepper Relish",
  slug: "roast-rack-of-lamb-with-roasted-red-pepper-relish",
  metadata: {
    timeBand: "NORMAL",
    estimatedMinutes: 145,
    equipmentTags: [
      "OVEN",
      "LARGE_SKILLET"
    ],
    leftoverStrategy: "EXPECTED",
    baseServings: 5,
    yieldText: "SERVES 4 to 6"
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "racks-of-lamb-13-4-to-2-pounds-each-fat-trimmed-to-1-8-to-1-4-inch-rib-bones-frenched",
          displayName: "racks of lamb (13/4 to 2 pounds each), fat trimmed to 1/8 to 1/4 inch, rib bones frenched",
          amount: 2,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "PROTEIN",
          shoppingCategory: "MEAT_SEAFOOD",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "kosher-salt-and-pepper",
          displayName: "Kosher salt and pepper",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "TO_TASTE"
        },
    {
          ingredientId: "ground-cumin",
          displayName: "ground cumin",
          amount: 1,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "vegetable-oil",
          displayName: "vegetable oil",
          amount: 1,
          unit: "TSP",
          criticality: "NON_CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "jarred-roasted-red-peppers-rinsed-patted-dry-and-chopped-fine",
          displayName: "jarred roasted red peppers, rinsed, patted dry, and chopped fine",
          amount: 0.5,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "RELISH"
        },
    {
          ingredientId: "minced-fresh-parsley",
          displayName: "minced fresh parsley",
          amount: 0.5,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          component: "RELISH"
        },
    {
          ingredientId: "extra-virgin-olive-oil",
          displayName: "extra-virgin olive oil",
          amount: 0.25,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "RELISH"
        },
    {
          ingredientId: "lemon-juice",
          displayName: "lemon juice",
          amount: 0.25,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "RELISH"
        },
    {
          ingredientId: "garlic-minced-to-paste",
          displayName: "garlic, minced to paste",
          amount: 0.125,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          component: "RELISH"
        },
    {
          ingredientId: "kosher-salt-and-pepper",
          displayName: "Kosher salt and pepper",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "TO_TASTE"
        }
  ],
  preflight: [
    {
          description: "Let relish stand at room temperature for at least 1 hour.",
          type: "LONG_PREP",
          durationMinutes: 60,
          optional: false,
          component: "RELISH"
        }
  ],
  steps: [
    {
          stepNumber: 1,
          instruction: "FOR THE LAMB: Adjust oven rack to middle position and heat oven to 250 degrees. Using sharp knife, cut slits in surface layer of fat, spaced 1/2-inch apart, in crosshatch pattern, being careful to cut down to, but not into, meat. Combine 2 tablespoons salt and cumin in bowl. Rub 3/4 teaspoon salt mixture over entire surface of each rack and into slits. Reserve remaining salt mixture for serving. Place racks, bone-side down, on wire rack set in rimmed baking sheet. Roast until meat registers 125 degrees for medium-rare or 130 degrees for medium, 1 hour 5 minutes to 1 hour 25 minutes."
        },
    {
          stepNumber: 2,
          instruction: "FOR THE RELISH: While lamb roasts, combine red peppers, parsley, olive oil, lemon juice, and garlic in bowl. Season with salt and pepper to taste. Let stand at room temperature at least 1 hour before serving."
        },
    {
          stepNumber: 3,
          instruction: "Heat vegetable oil in 12-inch skillet over high heat until just smoking. Place one rack, bone-side up, in skillet and cook until well-browned, 1 to 2 minutes. Transfer to carving board. Pour off all but 1 teaspoon fat from skillet and repeat with second rack. Tent racks loosely with aluminum foil and let rest for 20 minutes. Cut between ribs to separate chops and sprinkle cut side of chops with 1/2 teaspoon salt mixture. Serve, passing relish and remaining salt mixture separately."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ]
} satisfies Recipe;
