// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:24.512Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const sousVidePrimeRib = {
  id: "atk_sous-vide-prime-rib",
  name: "Sous Vide Prime Rib",
  slug: "sous-vide-prime-rib",
  metadata: {
    timeBand: "PROJECT",
    estimatedMinutes: 1020,
    equipmentTags: [
      "OVEN",
      "LARGE_SKILLET"
    ],
    leftoverStrategy: "EXPECTED",
    baseServings: 6,
    yieldText: "SERVES 6 to 8"
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "first-cut-beef-standing-rib-roast-3-bones",
          displayName: "first-cut beef standing rib roast (3 bones)",
          amount: 1,
          unit: "LB",
          criticality: "CRITICAL",
          kind: "PROTEIN",
          shoppingCategory: "MEAT_SEAFOOD",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "kosher-salt-and-pepper",
          displayName: "Kosher salt and pepper",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "TO_TASTE"
        },
    {
          ingredientId: "vegetable-oil",
          displayName: "vegetable oil",
          amount: 1,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        }
  ],
  preflight: [
    {
          description: "Salt and refrigerate the rib roast, uncovered, for at least 24 hours or up to 96 hours.",
          durationMinutes: 1440,
          type: "LONG_PREP"
        }
  ],
  steps: [
    {
          stepNumber: 1,
          instruction: "To remove bones from roast, use sharp knife and run it down length of bones, following contours as closely as possible; set bones aside. Cut slits in surface layer of fat on roast, spaced 1 inch apart, in crosshatch pattern, being careful to cut down to, but not into, meat. Rub 2 tablespoons salt over entire roast and into slits. Place meat back on bones (to save space in refrigerator), transfer to plate, and refrigerate, uncovered, at least 24 hours or up to 96 hours."
        },
    {
          stepNumber: 2,
          instruction: "Using sous vide circulator, bring water to 133°F/56°C in 12-quart container."
        },
    {
          stepNumber: 3,
          instruction: "Separate meat and bones; set aside bones. Heat oil in 12-inch skillet over medium-high heat until just smoking. Sear sides and top of roast until browned, 6 to 8 minutes (do not sear side where roast was cut from bone). Place meat back on ribs so bones fit where they were cut, and let cool for 10 minutes. Tie meat to bones between ribs with 2 lengths of kitchen twine."
        },
    {
          stepNumber: 4,
          instruction: "Season roast with pepper and place in 2-gallon zipper-lock freezer bag. Seal bag, pressing out as much air as possible. Gently lower bag into prepared water bath until roast is fully submerged, and then clip top corner of bag to side of water bath container, allowing remaining air bubbles to rise to top of bag. Reopen 1 corner of zipper, release remaining air bubbles, and reseal bag. Cover and cook for at least 16 hours or up to 24 hours."
        },
    {
          stepNumber: 5,
          instruction: "Adjust oven rack to middle position and heat broiler. Set wire rack in aluminum foil–lined rimmed baking sheet and spray with vegetable spray. Transfer roast, fat side up, to prepared rack and let rest for 10 to 15 minutes. Pat roast dry with paper towels. Broil until surface of roast is browned and crisp, 4 to 8 minutes."
        },
    {
          stepNumber: 6,
          instruction: "Transfer roast to carving board and discard ribs. Slice meat into 3/4-inch-thick slices. Serve."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ]
} satisfies Recipe;
