// Spec: recipe-spec.md §2.1, version 4.6.0
import type { Recipe } from '../types';

// Old-Fashioned Southern Meatloaf (Paula Deen)
// Source: https://www.pauladeen.com/recipe/old-fashioned-southern-meatloaf-recipe-aka-basic-meatloaf/
// Classic Southern comfort food with a sweet ketchup-brown sugar glaze.

export const southernMeatloafRecipe: Recipe = {
  id: 'r_southern_meatloaf',
  name: 'Old-Fashioned Southern Meatloaf',
  slug: 'southern-meatloaf',
  metadata: {
    timeBand: 'NORMAL',
    estimatedMinutes: 65,
    equipmentTags: ['OVEN', 'BAKING_DISH'],
    leftoverStrategy: 'EXPECTED',
  },
  ingredients: [
    {
      ingredientId: 'ing_ground_beef',
      displayName: 'Ground beef',
      amount: 1,
      unit: 'LB',
      criticality: 'CRITICAL',
      kind: 'PROTEIN',
      shoppingCategory: 'MEAT_SEAFOOD',
    },
    {
      ingredientId: 'ing_egg',
      displayName: 'Egg, lightly beaten',
      amount: 1,
      unit: 'UNIT',
      criticality: 'CRITICAL',
      kind: 'PROTEIN',
      shoppingCategory: 'DAIRY_EGGS',
    },
    {
      ingredientId: 'ing_quick_oats',
      displayName: 'Quick cooking oats',
      amount: 0.5,
      unit: 'CUP',
      criticality: 'CRITICAL',
      kind: 'CARB',
      shoppingCategory: 'PANTRY_DRY',
    },
    {
      ingredientId: 'ing_diced_tomatoes',
      displayName: 'Diced tomatoes, drained',
      amount: 8,
      unit: 'OZ',
      criticality: 'CRITICAL',
      kind: 'VEG',
      shoppingCategory: 'PANTRY_DRY',
    },
    {
      ingredientId: 'ing_chopped_onion',
      displayName: 'Chopped onion',
      amount: 0.5,
      unit: 'CUP',
      criticality: 'CRITICAL',
      kind: 'VEG',
      shoppingCategory: 'PRODUCE',
    },
    {
      ingredientId: 'ing_chopped_bell_pepper',
      displayName: 'Chopped bell pepper',
      amount: 0.5,
      unit: 'CUP',
      criticality: 'CRITICAL',
      kind: 'VEG',
      shoppingCategory: 'PRODUCE',
    },
    {
      ingredientId: 'ing_kosher_salt',
      displayName: 'Kosher salt',
      amount: 1.25,
      unit: 'TSP',
      criticality: 'NON_CRITICAL',
      kind: 'SPICE',
      shoppingCategory: 'PANTRY_DRY',
    },
    {
      ingredientId: 'ing_black_pepper',
      displayName: 'Ground black pepper',
      amount: 0.25,
      unit: 'TSP',
      criticality: 'NON_CRITICAL',
      kind: 'SPICE',
      shoppingCategory: 'PANTRY_DRY',
    },
    {
      ingredientId: 'ing_ketchup',
      displayName: 'Ketchup',
      amount: 0.33,
      unit: 'CUP',
      criticality: 'CRITICAL',
      kind: 'CONDIMENT',
      shoppingCategory: 'PANTRY_DRY',
    },
    {
      ingredientId: 'ing_brown_sugar',
      displayName: 'Brown sugar',
      amount: 2,
      unit: 'TBSP',
      criticality: 'CRITICAL',
      kind: 'OTHER',
      shoppingCategory: 'PANTRY_DRY',
    },
    {
      ingredientId: 'ing_yellow_mustard',
      displayName: 'Mustard',
      amount: 1,
      unit: 'TBSP',
      criticality: 'CRITICAL',
      kind: 'CONDIMENT',
      shoppingCategory: 'PANTRY_DRY',
    },
  ],
  preflight: [],
  steps: [
    { stepNumber: 1, instruction: 'Preheat oven to 375°F.' },
    { stepNumber: 2, instruction: 'Drain diced tomatoes well; discard liquid.' },
    { stepNumber: 3, instruction: 'In a bowl, combine ground beef, salt, pepper, onion, bell pepper, beaten egg, drained tomatoes, and oats; mix gently to combine.' },
    { stepNumber: 4, instruction: 'Shape mixture into a loaf in a baking dish.' },
    { stepNumber: 5, instruction: 'Stir together ketchup, brown sugar, and mustard; spread evenly over the loaf.' },
    { stepNumber: 6, instruction: 'Bake 60 minutes until internal temp reaches 160°F.' },
    { stepNumber: 7, instruction: 'Rest 5 minutes before slicing and serving.' },
  ],
  tags: ['comfort_food', 'american', 'southern', 'baked', 'family_dinner'],
  variantHints: [{ description: 'Swap ground beef for turkey for a lighter version.' }],
};
