// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:24.622Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const spanishTortillaWithRoastedRedPeppersAndPeas = {
  id: "atk_spanish-tortilla-with-roasted-red-peppers-and-peas",
  name: "Spanish Tortilla with Roasted Red Peppers and Peas",
  slug: "spanish-tortilla-with-roasted-red-peppers-and-peas",
  metadata: {
    timeBand: "NORMAL",
    estimatedMinutes: 60,
    leftoverStrategy: "EXPECTED",
    baseServings: 4,
    yieldText: "SERVES 4 to 6",
    equipmentTags: []
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "plus-1-teaspoon-extra-virgin-olive-oil-divided",
          displayName: "plus 1 teaspoon extra-virgin olive oil, divided",
          amount: 6,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "3-to-4-medium-yukon-gold-potatoes-peeled-quartered-and-cut-into-1-8-inch-thick-slices",
          displayName: "(3 to 4 medium) Yukon Gold potatoes, peeled, quartered, and cut into 1/8-inch-thick slices",
          amount: 1.5,
          unit: "LB",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "APPROXIMATE"
        },
    {
          ingredientId: "small-onion-halved-and-sliced-thin",
          displayName: "small onion, halved and sliced thin",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "table-salt-divided",
          displayName: "table salt, divided",
          amount: 1,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "pepper",
          displayName: "pepper",
          amount: 0.25,
          unit: "TSP",
          criticality: "NON_CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "large-eggs",
          displayName: "large eggs",
          amount: 8,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "jarred-roasted-red-peppers-rinsed-dried-and-cut-into-1-2-inch-pieces",
          displayName: "jarred roasted red peppers, rinsed, dried, and cut into 1/2-inch pieces",
          amount: 0.5,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "frozen-peas-thawed",
          displayName: "frozen peas, thawed",
          amount: 0.5,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "FROZEN",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "garlic-mayonnaise-optional-recipe-follows",
          displayName: "Garlic Mayonnaise (optional; recipe follows)",
          amount: 1,
          unit: "UNIT",
          criticality: "NON_CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "OTHER",
          quantityKind: "FIXED",
          component: "GARNISH"
        }
  ],
  preflight: [
    {
          description: "Thaw the frozen peas",
          durationMinutes: 30,
          optional: false,
          type: "LONG_PREP"
        }
  ],
  steps: [
    {
          stepNumber: 1,
          instruction: "Toss 1/4 cup oil, potatoes, onion, 1/2 teaspoon salt, and pepper in large bowl until potato slices are thoroughly separated and coated in oil. Heat 2 tablespoons oil in 10-inch nonstick skillet over medium-high heat until shimmering. Reduce heat to medium-low, add potato mixture to skillet, and set bowl aside (do not rinse). Cover and cook, stirring occasionally with heat-resistant rubber spatula, until potatoes offer no resistance when poked with paring knife, 22 to 28 minutes (some potato slices may break into smaller pieces)."
        },
    {
          stepNumber: 2,
          instruction: "Meanwhile, whisk eggs and remaining 1/2 teaspoon salt in reserved bowl until just combined. Using heat-resistant rubber spatula, fold hot potato mixture, red peppers, and peas into eggs until combined, making sure to scrape all of potato mixture out of skillet. Return skillet to medium-high heat, add remaining 1 teaspoon oil, and heat until just beginning to smoke. Add egg-potato mixture and cook, shaking pan and folding mixture constantly for 15 seconds; smooth top of mixture with heat-resistant rubber spatula. Reduce heat to medium, cover, and cook, gently shaking pan every 30 seconds, until bottom is golden brown and top is lightly set, about 2 minutes."
        },
    {
          stepNumber: 3,
          instruction: "Using heat-resistant rubber spatula, loosen tortilla from pan, shaking it back and forth until tortilla slides around. Slide tortilla onto large plate. Invert tortilla onto second large plate and slide it, browned side up, back into skillet. Tuck edges of tortilla into skillet. Return pan to medium heat and continue to cook, gently shaking pan every 30 seconds, until second side is golden brown, about 2 minutes longer. Slide tortilla onto cutting board; let cool for at least 15 minutes. Cut tortilla into cubes or wedges and serve with garlic mayonnaise, if using."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ]
} satisfies Recipe;
