// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:25.028Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const tacosDoradosCrispyGroundBeefTacos = {
  id: "atk_tacos-dorados-crispy-ground-beef-tacos",
  name: "Tacos Dorados (Crispy Ground Beef Tacos)",
  slug: "tacos-dorados-crispy-ground-beef-tacos",
  metadata: {
    timeBand: "NORMAL",
    estimatedMinutes: 75,
    equipmentTags: [
      "OVEN",
      "LARGE_SKILLET",
      "SHEET_PAN"
    ],
    leftoverStrategy: "EXPECTED",
    baseServings: 4,
    yieldText: "SERVES 4"
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "water",
          displayName: "water",
          amount: 1,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "baking-soda",
          displayName: "baking soda",
          amount: 0.25,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "90-percent-lean-ground-beef",
          displayName: "90 percent lean ground beef",
          amount: 12,
          unit: "OZ",
          criticality: "CRITICAL",
          kind: "PROTEIN",
          shoppingCategory: "MEAT_SEAFOOD",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "vegetable-oil-divided",
          displayName: "vegetable oil, divided",
          amount: 7,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "onion-chopped-fine",
          displayName: "onion, chopped fine",
          amount: 1,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "chili-powder",
          displayName: "chili powder",
          amount: 1.5,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "paprika",
          displayName: "paprika",
          amount: 1.5,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "ground-cumin",
          displayName: "ground cumin",
          amount: 1.5,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "garlic-powder",
          displayName: "garlic powder",
          amount: 1.5,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "table-salt",
          displayName: "table salt",
          amount: 1,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "tomato-paste",
          displayName: "tomato paste",
          amount: 2,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "cheddar-cheese-shredded-1-2-cup-plus-extra-for-serving",
          displayName: "cheddar cheese, shredded (1/2 cup), plus extra for serving",
          amount: 2,
          unit: "OZ",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          component: "FILLING",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "6-inch-corn-tortillas",
          displayName: "(6-inch) corn tortillas",
          amount: 12,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "CARB",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "shredded-iceberg-lettuce",
          displayName: "Shredded iceberg lettuce",
          amount: 1,
          unit: "UNIT",
          criticality: "NON_CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          component: "GARNISH"
        },
    {
          ingredientId: "chopped-tomato",
          displayName: "Chopped tomato",
          amount: 1,
          unit: "UNIT",
          criticality: "NON_CRITICAL",
          kind: "VEG",
          shoppingCategory: "PRODUCE",
          quantityKind: "FIXED",
          component: "GARNISH"
        },
    {
          ingredientId: "sour-cream",
          displayName: "Sour cream",
          amount: 1,
          unit: "UNIT",
          criticality: "NON_CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          component: "GARNISH",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "pickled-jalape-o-slices",
          displayName: "Pickled jalapeño slices",
          amount: 1,
          unit: "UNIT",
          criticality: "NON_CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "GARNISH"
        },
    {
          ingredientId: "hot-sauce",
          displayName: "Hot sauce",
          amount: 1,
          unit: "UNIT",
          criticality: "NON_CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "GARNISH"
        }
  ],
  preflight: [],
  steps: [
    {
          stepNumber: 1,
          instruction: "Adjust oven rack to middle position and heat oven to 400 degrees. Combine water and baking soda in large bowl. Add beef and mix until thoroughly combined. Set aside."
        },
    {
          stepNumber: 2,
          instruction: "Heat 1 tablespoon oil in 12-inch nonstick skillet over medium heat until shimmering. Add onion and cook, stirring occasionally, until softened, 4 to 6 minutes. Add chili powder, paprika, cumin, garlic powder, and salt and cook, stirring frequently, until fragrant, about 1 minute. Stir in tomato paste and cook until paste is rust-colored, 1 to 2 minutes. Add beef mixture and cook, using wooden spoon to break meat into pieces no larger than 1/4 inch, until beef is no longer pink, 5 to 7 minutes. Transfer beef mixture to bowl; stir in cheddar until cheese has melted and mixture is homogeneous. Wipe skillet clean with paper towels."
        },
    {
          stepNumber: 3,
          instruction: "Thoroughly brush both sides of tortillas with 2 tablespoons oil. Arrange tortillas, overlapping, on rimmed baking sheet in 2 rows (6 tortillas each). Bake until tortillas are warm and pliable, about 5 minutes. Remove tortillas from oven and reduce oven temperature to 200 degrees."
        },
    {
          stepNumber: 4,
          instruction: "Place 2 tablespoons filling on 1 side of 1 tortilla. Fold and press to close tortilla (edges will be open, but tortilla will remain folded). Repeat with remaining tortillas and remaining filling. (Filled tortillas can be wrapped in foil and refrigerated for up to 12 hours.)"
        },
    {
          stepNumber: 5,
          instruction: "Set wire rack in second rimmed baking sheet and line rack with double layer of paper towels. Heat remaining 1/4 cup oil in now-empty skillet over medium-high heat until shimmering. Arrange 6 tacos in skillet with open sides facing away from you. Cook, adjusting heat so oil actively sizzles and bubbles appear around edges of tacos, until tacos are crispy and deeply browned on 1 side, 2 to 3 minutes. Using tongs and thin spatula, carefully flip tacos. Cook until deeply browned on second side, 2 to 3 minutes, adjusting heat as necessary."
        },
    {
          stepNumber: 6,
          instruction: "Remove skillet from heat and transfer tacos to prepared wire rack. Blot tops of tacos with double layer of paper towels. Place sheet with fried tacos in oven to keep warm. Return skillet to medium-high heat and cook remaining tacos. Serve tacos immediately, passing extra cheddar, lettuce, tomato, sour cream, jalapeños, and hot sauce separately."
        },
    {
          stepNumber: 7,
          instruction: "Brush corn tortillas with oil; bake until pliable enough to stuff. Stuff warmed tortillas with savory ground beef bound together with melted cheddar cheese."
        },
    {
          stepNumber: 8,
          instruction: "Fry tacos in 2 batches until crispy. (Only 1/4 cup of oil is needed for 12 tacos.)"
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ],
  recipeAllergens: [
    "DAIRY"
  ]
} satisfies Recipe;
