// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:25.255Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const tiramisu = {
  id: "atk_tiramisu",
  name: "Tiramisu",
  slug: "tiramisu",
  metadata: {
    timeBand: "NORMAL",
    estimatedMinutes: 45,
    equipmentTags: [
      "BAKING_DISH"
    ],
    leftoverStrategy: "EXPECTED",
    baseServings: 11,
    yieldText: "SERVES 10 to 12"
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "strong-brewed-coffee-room-temperature",
          displayName: "strong brewed coffee, room temperature",
          amount: 2.5,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "dark-rum-divided",
          displayName: "dark rum, divided",
          amount: 9,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "instant-espresso-powder",
          displayName: "instant espresso powder",
          amount: 1.5,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "large-egg-yolks-room-temperature",
          displayName: "large egg yolks, room temperature",
          amount: 6,
          unit: "UNIT",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          allergens: [
            "EGG"
          ]
        },
    {
          ingredientId: "42-3-ounces-sugar",
          displayName: "(42/3 ounces) sugar",
          amount: 0.6666666666666666,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "table-salt",
          displayName: "table salt",
          amount: 0.25,
          unit: "TSP",
          criticality: "NON_CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "mascarpone-generous-3-cups",
          displayName: "mascarpone (generous 3 cups)",
          amount: 1.5,
          unit: "LB",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "heavy-cream-chilled",
          displayName: "heavy cream, chilled",
          amount: 0.75,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "42-to-60-depending-on-size-dried-ladyfingers",
          displayName: "(42 to 60, depending on size) dried ladyfingers",
          amount: 14,
          unit: "OZ",
          criticality: "CRITICAL",
          kind: "CARB",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "cocoa-powder-preferably-dutch-processed-divided",
          displayName: "cocoa powder, preferably Dutch-processed, divided",
          amount: 3.5,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          component: "DUSTING"
        },
    {
          ingredientId: "grated-semisweet-or-bittersweet-chocolate-optional",
          displayName: "grated semisweet or bittersweet chocolate (optional)",
          amount: 0.25,
          unit: "CUP",
          criticality: "NON_CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "APPROXIMATE",
          component: "GARNISH"
        }
  ],
  preflight: [
    {
          name: "Refrigerate",
          description: "Refrigerate for 6 to 24 hours.",
          durationMinutes: 360,
          optional: false,
          type: "LONG_PREP"
        }
  ],
  steps: [
    {
          stepNumber: 1,
          instruction: "Stir together coffee, 5 tablespoons rum, and espresso powder in wide bowl or baking dish until espresso dissolves; set aside."
        },
    {
          stepNumber: 2,
          instruction: "Using stand mixer fitted with whisk attachment, beat egg yolks at low speed until just combined. Add sugar and salt and beat at medium-high speed until pale yellow, 11/2 to 2 minutes, scraping down sides of bowl with rubber spatula once or twice. Add remaining 1/4 cup rum and beat at medium speed until just combined, 20 to 30 seconds; scrape bowl. Add mascarpone and beat at medium speed until no lumps remain, 30 to 45 seconds, scraping down sides of bowl once or twice. Transfer mixture to large bowl and set aside."
        },
    {
          stepNumber: 3,
          instruction: "In now-empty mixer bowl, beat cream at medium speed until frothy, 1 to 11/2 minutes. Increase speed to high and continue to beat until cream holds stiff peaks, 1 to 11/2 minutes longer. Using rubber spatula, fold one-third of whipped cream into mascarpone mixture to lighten, then gently fold in remaining whipped cream until no white streaks remain. Set mascarpone mixture aside."
        },
    {
          stepNumber: 4,
          instruction: "Working with one at a time, drop half of ladyfingers into coffee mixture, roll, remove, and transfer to 13 by 9-inch glass or ceramic baking dish. (Do not submerge ladyfingers in coffee mixture; entire process should take no longer than 2 to 3 seconds for each cookie.) Arrange soaked cookies in single layer in baking dish, breaking or trimming ladyfingers as needed to fit neatly into dish."
        },
    {
          stepNumber: 5,
          instruction: "Spread half of mascarpone mixture over ladyfingers; use rubber spatula to spread mixture to sides and into corners of dish and smooth the surface. Place 2 tablespoons cocoa in fine-mesh strainer and dust cocoa over mascarpone."
        },
    {
          stepNumber: 6,
          instruction: "Repeat dipping and arrangement of ladyfingers; spread remaining mascarpone mixture over ladyfingers and dust with remaining 11/2 tablespoons cocoa. Wipe edges of dish with dry paper towel. Cover with plastic wrap and refrigerate for 6 to 24 hours. Sprinkle with grated chocolate, if using; cut into pieces and serve chilled."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ],
  recipeAllergens: [
    "EGG",
    "DAIRY"
  ]
} satisfies Recipe;
