// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:25.394Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const ultimateFlakyButtermilkBiscuits = {
  id: "atk_ultimate-flaky-buttermilk-biscuits",
  name: "Ultimate Flaky Buttermilk Biscuits",
  slug: "ultimate-flaky-buttermilk-biscuits",
  metadata: {
    timeBand: "NORMAL",
    estimatedMinutes: 75,
    equipmentTags: [
      "SHEET_PAN"
    ],
    leftoverStrategy: "COOK_ONCE_EAT_TWICE",
    yieldText: "MAKES 9 biscuits",
    baseServings: 9
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "15-ounces-king-arthur-all-purpose-flour",
          displayName: "(15 ounces) King Arthur all-purpose flour",
          amount: 3,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "CARB",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "sugar",
          displayName: "sugar",
          amount: 2,
          unit: "TBSP",
          criticality: "NON_CRITICAL",
          kind: "CARB",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "baking-powder",
          displayName: "baking powder",
          amount: 4,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "baking-soda",
          displayName: "baking soda",
          amount: 0.5,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "table-salt",
          displayName: "table salt",
          amount: 1.5,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "2-sticks-unsalted-butter-frozen-for-30-minutes-divided",
          displayName: "(2 sticks) unsalted butter, frozen for 30 minutes, divided",
          amount: 16,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "buttermilk-chilled",
          displayName: "buttermilk, chilled",
          amount: 1.25,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        }
  ],
  preflight: [
    {
          description: "Freeze butter for 30 minutes",
          durationMinutes: 30,
          criticality: "CRITICAL",
          type: "LONG_PREP"
        }
  ],
  steps: [
    {
          stepNumber: 1,
          instruction: "Line rimmed baking sheet with parchment paper and set aside. Whisk flour, sugar, baking powder, baking soda, and salt together in large bowl. Coat sticks of butter in flour mixture, then grate 7 tablespoons from each stick on large holes of box grater directly into flour mixture. Toss gently to combine. Set aside remaining 2 tablespoons butter."
        },
    {
          stepNumber: 2,
          instruction: "Add buttermilk to flour mixture and fold with spatula until just combined (dough will look dry). Transfer dough to liberally floured counter. Dust surface of dough with flour; using your floured hands, press dough into rough 7-inch square."
        },
    {
          stepNumber: 3,
          instruction: "Roll dough into 12 by 9-inch rectangle with short side parallel to edge of counter. Starting at bottom of dough, fold into thirds like business letter, using bench scraper or metal spatula to release dough from counter. Press top of dough firmly to seal folds. Turn dough 90 degrees clockwise. Repeat rolling into 12 by 9-inch rectangle, folding into thirds, and turning clockwise 4 more times, for total of 5 sets of folds. After last set of folds, roll dough into 81/2-inch square about 1 inch thick. Transfer dough to prepared sheet, cover with plastic wrap, and refrigerate for 30 minutes. Adjust oven rack to upper-middle position and heat oven to 400 degrees."
        },
    {
          stepNumber: 4,
          instruction: "Transfer dough to lightly floured cutting board. Using sharp, floured chef’s knife, trim 1/4 inch of dough from each side of square and discard. Cut remaining dough into 9 squares, flouring knife after each cut. Arrange biscuits at least 1 inch apart on sheet. Melt reserved butter; brush tops of biscuits with melted butter."
        },
    {
          stepNumber: 5,
          instruction: "Bake until tops are golden brown, 22 to 25 minutes, rotating sheet halfway through baking. Transfer biscuits to wire rack and let cool for 15 minutes before serving."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ],
  recipeAllergens: [
    "DAIRY"
  ]
} satisfies Recipe;
