// Generated by scripts/spoonacular-workflow.ts on 2025-12-11T21:45:25.555Z
// Source: promoted from src/dev/imported (provenance preserved there)
// ⚠️  This is a canonical recipe file. Edit manually or regenerate with workflow.

import { Recipe } from '../types';

export const wholeWheatSandwichBread = {
  id: "atk_whole-wheat-sandwich-bread",
  name: "Whole-Wheat Sandwich Bread",
  slug: "whole-wheat-sandwich-bread",
  metadata: {
    timeBand: "PROJECT",
    estimatedMinutes: 420,
    leftoverStrategy: "EXPECTED",
    yieldText: "MAKES two 8-inch loaves",
    baseServings: 2,
    equipmentTags: []
  },
  scalable: true,
  ingredients: [
    {
          ingredientId: "11-ounces-bread-flour",
          displayName: "(11 ounces) bread flour",
          amount: 2,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "CARB",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "water-heated-to-110-degrees",
          displayName: "water, heated to 110 degrees",
          amount: 1,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "instant-or-rapid-rise-yeast",
          displayName: "instant or rapid-rise yeast",
          amount: 0.5,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "161-2-ounces-whole-wheat-flour",
          displayName: "(161/2 ounces) whole-wheat flour",
          amount: 3,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "CARB",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          allergens: [
            "WHEAT"
          ]
        },
    {
          ingredientId: "wheat-germ",
          displayName: "wheat germ",
          amount: 0.5,
          unit: "CUP",
          criticality: "NON_CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED",
          allergens: [
            "WHEAT"
          ]
        },
    {
          ingredientId: "whole-milk",
          displayName: "whole milk",
          amount: 2,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "DAIRY",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "unsalted-butter-softened",
          displayName: "unsalted butter, softened",
          amount: 6,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "DAIRY_EGGS",
          quantityKind: "FIXED",
          allergens: [
            "DAIRY"
          ]
        },
    {
          ingredientId: "honey",
          displayName: "honey",
          amount: 0.25,
          unit: "CUP",
          criticality: "CRITICAL",
          kind: "CONDIMENT",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "instant-or-rapid-rise-yeast",
          displayName: "instant or rapid-rise yeast",
          amount: 2,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "OTHER",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "vegetable-oil",
          displayName: "vegetable oil",
          amount: 2,
          unit: "TBSP",
          criticality: "CRITICAL",
          kind: "FAT_OIL",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        },
    {
          ingredientId: "table-salt",
          displayName: "table salt",
          amount: 4,
          unit: "TSP",
          criticality: "CRITICAL",
          kind: "SPICE",
          shoppingCategory: "PANTRY_DRY",
          quantityKind: "FIXED"
        }
  ],
  preflight: [
    {
          stepNumbers: [
            1
          ],
          hoursBefore: 8,
          type: "LONG_PREP",
          description: "Combine ingredients for the sponge. Let sit at room temperature for at least 8 hours or up to 24 hours.",
          optional: false
        },
    {
          stepNumbers: [
            2
          ],
          hoursBefore: 8,
          type: "LONG_PREP",
          description: "Combine ingredients for the soaker. Refrigerate for at least 8 hours or up to 24 hours.",
          optional: false
        }
  ],
  steps: [
    {
          stepNumber: 1,
          instruction: "FOR THE SPONGE: Combine the flour, water, and yeast in a large bowl and stir with a wooden spoon until a uniform mass forms and no dry flour remains, about 1 minute. Cover the bowl tightly with plastic wrap and let sit at room temperature for at least 8 hours or up to 24 hours."
        },
    {
          stepNumber: 2,
          instruction: "FOR THE SOAKER: Combine the flour, wheat germ, and milk in a separate large bowl and stir with a wooden spoon until a shaggy mass forms, about 1 minute. Transfer the dough to a lightly floured work surface and knead by hand until smooth, 2 to 3 minutes. Return the soaker to the bowl, cover tightly with plastic wrap, and refrigerate for at least 8 hours or up to 24 hours."
        },
    {
          stepNumber: 3,
          instruction: "FOR THE DOUGH: Tear the soaker apart into 1-inch pieces and place in the bowl of a stand mixer fitted with the dough hook. Add the sponge, butter, honey, yeast, oil, and salt and mix on low speed until a cohesive mass starts to form, about 2 minutes. Increase the speed to medium and knead until the dough is smooth and elastic, 8 to 10 minutes. Transfer the dough to a lightly floured work surface and knead by hand to form a smooth, round ball, about 1 minute. Place the dough in a large, lightly greased bowl. Cover tightly with plastic wrap and let rise at room temperature for 45 minutes."
        },
    {
          stepNumber: 4,
          instruction: "Gently press down on the center of the dough to deflate. Spray a rubber spatula or bowl scraper with vegetable oil spray; fold the partially risen dough over itself by gently lifting and folding the edge of the dough toward the middle. Turn the bowl 90 degrees; fold again. Turn the bowl and fold the dough 6 more times (for a total of 8 folds). Cover tightly with plastic wrap and allow to rise at room temperature until doubled in size, about 45 minutes."
        },
    {
          stepNumber: 5,
          instruction: "Grease two 81/2 by 41/2-inch loaf pans. Transfer the dough to a well-floured work surface and divide in half. Press 1 piece of the dough into a 17 by 8-inch rectangle, with the short side facing you. Roll the dough toward you into a firm cylinder, keeping the roll taut by tucking it under itself as you go. Turn the loaf seam side up and pinch it closed. Place the loaf seam side down in a prepared pan, pressing gently into the corners. Repeat with the second piece of dough. Cover the loaves loosely with greased plastic wrap and let rise at room temperature until nearly doubled in size, 1 to 11/2 hours (the top of the loaves should rise about 1 inch over the lip of the pan)."
        },
    {
          stepNumber: 6,
          instruction: "Thirty minutes before baking, adjust the oven racks to the middle and lowest positions, place a baking stone on the middle rack, place an empty loaf pan or other heatproof pan on the bottom rack, and heat the oven to 400 degrees. Bring 2 cups water to boil on the stovetop."
        },
    {
          stepNumber: 7,
          instruction: "Using a sharp serrated knife or a single-edge razor blade, make one 1/4-inch-deep slash lengthwise down the center of each loaf. Working quickly, pour the boiling water into the empty loaf pan in the oven and set the loaves on the baking stone. Reduce the oven temperature to 350 degrees. Bake until the crust is dark brown and the loaves register 200 degrees on an instant-read thermometer, 40 to 50 minutes, rotating the loaves front to back and side to side halfway through baking. Transfer the pans to a wire rack and let cool for 5 minutes. Remove the loaves from the pans, return to the rack, and let cool to room temperature, about 2 hours, before slicing and serving. Bread can be wrapped in a double layer of plastic wrap and stored at room temperature for up to 3 days; wrapped with an additional layer of aluminum foil, the bread can be frozen for up to 1 month."
        },
    {
          stepNumber: 8,
          instruction: "Deflate the center of the dough, then fold it in on itself. Turn the bowl 90 degrees; fold again. Repeat for a total of 8 folds. Let rise for 45 minutes."
        },
    {
          stepNumber: 9,
          instruction: "Halve the dough and pat each portion into an 8 by 17-inch rectangle, with the short side facing you."
        },
    {
          stepNumber: 10,
          instruction: "Roll each sheet toward you into a tight cylinder. Keep the roll taut by tucking it under itself as you go. Pinch the seams to seal."
        },
    {
          stepNumber: 11,
          instruction: "Place each loaf seam side down in the prepared loaf pans. Let the dough rise until almost doubled in size, 60 to 90 minutes."
        },
    {
          stepNumber: 12,
          instruction: "Using a knife, make a shallow slash down the center of each loaf to stop the bread from tearing when it rises. Bake for 40 to 50 minutes."
        }
  ],
  tags: [
    "atk_source",
    "american",
    "comfort_food"
  ],
  recipeAllergens: [
    "WHEAT",
    "DAIRY"
  ]
} satisfies Recipe;
